/*
 * generated by Xtext 2.10.0
 */
package co.edu.uniandes.services;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.List;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Alternatives;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.CrossReference;
import org.eclipse.xtext.Grammar;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.Group;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.common.services.TerminalsGrammarAccess;
import org.eclipse.xtext.service.AbstractElementFinder.AbstractGrammarElementFinder;
import org.eclipse.xtext.service.GrammarProvider;

@Singleton
public class KPIGeneratorGrammarAccess extends AbstractGrammarElementFinder {
	
	public class TaskElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "co.edu.uniandes.KPIGenerator.Task");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cTaskAction_0 = (Action)cGroup.eContents().get(0);
		private final Assignment cIdAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cIdINTTerminalRuleCall_1_0 = (RuleCall)cIdAssignment_1.eContents().get(0);
		private final RuleCall cSEMICOLONTerminalRuleCall_2 = (RuleCall)cGroup.eContents().get(2);
		private final Assignment cProjectAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cProjectCADENATerminalRuleCall_3_0 = (RuleCall)cProjectAssignment_3.eContents().get(0);
		private final RuleCall cSEMICOLONTerminalRuleCall_4 = (RuleCall)cGroup.eContents().get(4);
		private final Assignment cMilestoneAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cMilestoneCADENATerminalRuleCall_5_0 = (RuleCall)cMilestoneAssignment_5.eContents().get(0);
		private final RuleCall cSEMICOLONTerminalRuleCall_6 = (RuleCall)cGroup.eContents().get(6);
		private final Assignment cNameAssignment_7 = (Assignment)cGroup.eContents().get(7);
		private final RuleCall cNameCADENATerminalRuleCall_7_0 = (RuleCall)cNameAssignment_7.eContents().get(0);
		private final RuleCall cSEMICOLONTerminalRuleCall_8 = (RuleCall)cGroup.eContents().get(8);
		private final Assignment cTaskDescriptionAssignment_9 = (Assignment)cGroup.eContents().get(9);
		private final RuleCall cTaskDescriptionCADENATerminalRuleCall_9_0 = (RuleCall)cTaskDescriptionAssignment_9.eContents().get(0);
		private final RuleCall cSEMICOLONTerminalRuleCall_10 = (RuleCall)cGroup.eContents().get(10);
		private final Assignment cStartDateAssignment_11 = (Assignment)cGroup.eContents().get(11);
		private final RuleCall cStartDateDATETerminalRuleCall_11_0 = (RuleCall)cStartDateAssignment_11.eContents().get(0);
		private final RuleCall cSEMICOLONTerminalRuleCall_12 = (RuleCall)cGroup.eContents().get(12);
		private final Assignment cDueDateAssignment_13 = (Assignment)cGroup.eContents().get(13);
		private final RuleCall cDueDateDATETerminalRuleCall_13_0 = (RuleCall)cDueDateAssignment_13.eContents().get(0);
		private final RuleCall cSEMICOLONTerminalRuleCall_14 = (RuleCall)cGroup.eContents().get(14);
		private final Assignment cPriorityAssignment_15 = (Assignment)cGroup.eContents().get(15);
		private final RuleCall cPrioritySTRINGTerminalRuleCall_15_0 = (RuleCall)cPriorityAssignment_15.eContents().get(0);
		private final RuleCall cSEMICOLONTerminalRuleCall_16 = (RuleCall)cGroup.eContents().get(16);
		private final Assignment cPrivateAssignment_17 = (Assignment)cGroup.eContents().get(17);
		private final RuleCall cPrivateBOOLParserRuleCall_17_0 = (RuleCall)cPrivateAssignment_17.eContents().get(0);
		private final RuleCall cSEMICOLONTerminalRuleCall_18 = (RuleCall)cGroup.eContents().get(18);
		private final Assignment cProgressAssignment_19 = (Assignment)cGroup.eContents().get(19);
		private final RuleCall cProgressINTTerminalRuleCall_19_0 = (RuleCall)cProgressAssignment_19.eContents().get(0);
		private final RuleCall cSEMICOLONTerminalRuleCall_20 = (RuleCall)cGroup.eContents().get(20);
		private final Assignment cTaskAssignment_21 = (Assignment)cGroup.eContents().get(21);
		private final RuleCall cTaskStatusParserRuleCall_21_0 = (RuleCall)cTaskAssignment_21.eContents().get(0);
		private final RuleCall cSEMICOLONTerminalRuleCall_22 = (RuleCall)cGroup.eContents().get(22);
		private final Assignment cAssignedToAssignment_23 = (Assignment)cGroup.eContents().get(23);
		private final RuleCall cAssignedToCADENATerminalRuleCall_23_0 = (RuleCall)cAssignedToAssignment_23.eContents().get(0);
		private final RuleCall cSEMICOLONTerminalRuleCall_24 = (RuleCall)cGroup.eContents().get(24);
		private final Assignment cCreatedDateAssignment_25 = (Assignment)cGroup.eContents().get(25);
		private final RuleCall cCreatedDateDATEHOURTerminalRuleCall_25_0 = (RuleCall)cCreatedDateAssignment_25.eContents().get(0);
		private final RuleCall cSEMICOLONTerminalRuleCall_26 = (RuleCall)cGroup.eContents().get(26);
		private final RuleCall cCADENATerminalRuleCall_27 = (RuleCall)cGroup.eContents().get(27);
		private final RuleCall cSEMICOLONTerminalRuleCall_28 = (RuleCall)cGroup.eContents().get(28);
		private final RuleCall cCADENATerminalRuleCall_29 = (RuleCall)cGroup.eContents().get(29);
		private final RuleCall cSEMICOLONTerminalRuleCall_30 = (RuleCall)cGroup.eContents().get(30);
		private final Assignment cCompletedDateAssignment_31 = (Assignment)cGroup.eContents().get(31);
		private final RuleCall cCompletedDateDATEHOURTerminalRuleCall_31_0 = (RuleCall)cCompletedDateAssignment_31.eContents().get(0);
		private final RuleCall cSEMICOLONTerminalRuleCall_32 = (RuleCall)cGroup.eContents().get(32);
		private final RuleCall cCADENATerminalRuleCall_33 = (RuleCall)cGroup.eContents().get(33);
		private final RuleCall cSEMICOLONTerminalRuleCall_34 = (RuleCall)cGroup.eContents().get(34);
		private final RuleCall cCADENATerminalRuleCall_35 = (RuleCall)cGroup.eContents().get(35);
		private final RuleCall cSEMICOLONTerminalRuleCall_36 = (RuleCall)cGroup.eContents().get(36);
		private final Assignment cTimeLoggedAssignment_37 = (Assignment)cGroup.eContents().get(37);
		private final RuleCall cTimeLoggedINTTerminalRuleCall_37_0 = (RuleCall)cTimeLoggedAssignment_37.eContents().get(0);
		private final RuleCall cSEMICOLONTerminalRuleCall_38 = (RuleCall)cGroup.eContents().get(38);
		private final Assignment cBillableMinutesAssignment_39 = (Assignment)cGroup.eContents().get(39);
		private final RuleCall cBillableMinutesINTTerminalRuleCall_39_0 = (RuleCall)cBillableMinutesAssignment_39.eContents().get(0);
		private final RuleCall cSEMICOLONTerminalRuleCall_40 = (RuleCall)cGroup.eContents().get(40);
		private final Assignment cParentTaskAssignment_41 = (Assignment)cGroup.eContents().get(41);
		private final CrossReference cParentTaskTaskCrossReference_41_0 = (CrossReference)cParentTaskAssignment_41.eContents().get(0);
		private final RuleCall cParentTaskTaskIDTerminalRuleCall_41_0_1 = (RuleCall)cParentTaskTaskCrossReference_41_0.eContents().get(1);
		private final RuleCall cSEMICOLONTerminalRuleCall_42 = (RuleCall)cGroup.eContents().get(42);
		private final Assignment cCompletedOnTimeAssignment_43 = (Assignment)cGroup.eContents().get(43);
		private final RuleCall cCompletedOnTimeBOOLParserRuleCall_43_0 = (RuleCall)cCompletedOnTimeAssignment_43.eContents().get(0);
		private final RuleCall cSEMICOLONTerminalRuleCall_44 = (RuleCall)cGroup.eContents().get(44);
		private final Assignment cTimeEstimatedAssignment_45 = (Assignment)cGroup.eContents().get(45);
		private final RuleCall cTimeEstimatedINTTerminalRuleCall_45_0 = (RuleCall)cTimeEstimatedAssignment_45.eContents().get(0);
		private final RuleCall cSEMICOLONTerminalRuleCall_46 = (RuleCall)cGroup.eContents().get(46);
		private final Assignment cTagsAssignment_47 = (Assignment)cGroup.eContents().get(47);
		private final RuleCall cTagsCADENATerminalRuleCall_47_0 = (RuleCall)cTagsAssignment_47.eContents().get(0);
		private final RuleCall cNEWLINETerminalRuleCall_48 = (RuleCall)cGroup.eContents().get(48);
		
		//Task:
		//	{Task} id=INT
		//	SEMICOLON
		//	project=CADENA
		//	SEMICOLON
		//	milestone=CADENA?
		//	SEMICOLON
		//	name=CADENA
		//	SEMICOLON
		//	TaskDescription=CADENA?
		//	SEMICOLON
		//	startDate=DATE
		//	SEMICOLON
		//	DueDate=DATE
		//	SEMICOLON
		//	priority=STRING?
		//	SEMICOLON
		//	private=BOOL
		//	SEMICOLON
		//	progress=INT
		//	SEMICOLON
		//	Task+=Status
		//	SEMICOLON
		//	assignedTo=CADENA
		//	SEMICOLON
		//	createdDate=DATEHOUR
		//	SEMICOLON
		//	CADENA //Created By Firstname
		//	SEMICOLON
		//	CADENA // Created By Lastname
		//	SEMICOLON
		//	completedDate=DATEHOUR
		//	SEMICOLON
		//	CADENA //Completed By Firstname
		//	SEMICOLON
		//	CADENA //Completed By Lastname
		//	SEMICOLON
		//	timeLogged=INT?
		//	SEMICOLON
		//	billableMinutes=INT?
		//	SEMICOLON
		//	parentTask=[Task]?
		//	SEMICOLON
		//	completedOnTime=BOOL
		//	SEMICOLON
		//	timeEstimated=INT
		//	SEMICOLON
		//	tags=CADENA?
		//	NEWLINE;
		@Override public ParserRule getRule() { return rule; }
		
		//{Task} id=INT SEMICOLON project=CADENA SEMICOLON milestone=CADENA? SEMICOLON name=CADENA SEMICOLON
		//TaskDescription=CADENA? SEMICOLON startDate=DATE SEMICOLON DueDate=DATE SEMICOLON priority=STRING? SEMICOLON
		//private=BOOL SEMICOLON progress=INT SEMICOLON Task+=Status SEMICOLON assignedTo=CADENA SEMICOLON createdDate=DATEHOUR
		//SEMICOLON CADENA //Created By Firstname
		//SEMICOLON CADENA // Created By Lastname
		//SEMICOLON completedDate=DATEHOUR SEMICOLON CADENA //Completed By Firstname
		//SEMICOLON CADENA //Completed By Lastname
		//SEMICOLON timeLogged=INT? SEMICOLON billableMinutes=INT? SEMICOLON parentTask=[Task]? SEMICOLON completedOnTime=BOOL
		//SEMICOLON timeEstimated=INT SEMICOLON tags=CADENA? NEWLINE
		public Group getGroup() { return cGroup; }
		
		//{Task}
		public Action getTaskAction_0() { return cTaskAction_0; }
		
		//id=INT
		public Assignment getIdAssignment_1() { return cIdAssignment_1; }
		
		//INT
		public RuleCall getIdINTTerminalRuleCall_1_0() { return cIdINTTerminalRuleCall_1_0; }
		
		//SEMICOLON
		public RuleCall getSEMICOLONTerminalRuleCall_2() { return cSEMICOLONTerminalRuleCall_2; }
		
		//project=CADENA
		public Assignment getProjectAssignment_3() { return cProjectAssignment_3; }
		
		//CADENA
		public RuleCall getProjectCADENATerminalRuleCall_3_0() { return cProjectCADENATerminalRuleCall_3_0; }
		
		//SEMICOLON
		public RuleCall getSEMICOLONTerminalRuleCall_4() { return cSEMICOLONTerminalRuleCall_4; }
		
		//milestone=CADENA?
		public Assignment getMilestoneAssignment_5() { return cMilestoneAssignment_5; }
		
		//CADENA
		public RuleCall getMilestoneCADENATerminalRuleCall_5_0() { return cMilestoneCADENATerminalRuleCall_5_0; }
		
		//SEMICOLON
		public RuleCall getSEMICOLONTerminalRuleCall_6() { return cSEMICOLONTerminalRuleCall_6; }
		
		//name=CADENA
		public Assignment getNameAssignment_7() { return cNameAssignment_7; }
		
		//CADENA
		public RuleCall getNameCADENATerminalRuleCall_7_0() { return cNameCADENATerminalRuleCall_7_0; }
		
		//SEMICOLON
		public RuleCall getSEMICOLONTerminalRuleCall_8() { return cSEMICOLONTerminalRuleCall_8; }
		
		//TaskDescription=CADENA?
		public Assignment getTaskDescriptionAssignment_9() { return cTaskDescriptionAssignment_9; }
		
		//CADENA
		public RuleCall getTaskDescriptionCADENATerminalRuleCall_9_0() { return cTaskDescriptionCADENATerminalRuleCall_9_0; }
		
		//SEMICOLON
		public RuleCall getSEMICOLONTerminalRuleCall_10() { return cSEMICOLONTerminalRuleCall_10; }
		
		//startDate=DATE
		public Assignment getStartDateAssignment_11() { return cStartDateAssignment_11; }
		
		//DATE
		public RuleCall getStartDateDATETerminalRuleCall_11_0() { return cStartDateDATETerminalRuleCall_11_0; }
		
		//SEMICOLON
		public RuleCall getSEMICOLONTerminalRuleCall_12() { return cSEMICOLONTerminalRuleCall_12; }
		
		//DueDate=DATE
		public Assignment getDueDateAssignment_13() { return cDueDateAssignment_13; }
		
		//DATE
		public RuleCall getDueDateDATETerminalRuleCall_13_0() { return cDueDateDATETerminalRuleCall_13_0; }
		
		//SEMICOLON
		public RuleCall getSEMICOLONTerminalRuleCall_14() { return cSEMICOLONTerminalRuleCall_14; }
		
		//priority=STRING?
		public Assignment getPriorityAssignment_15() { return cPriorityAssignment_15; }
		
		//STRING
		public RuleCall getPrioritySTRINGTerminalRuleCall_15_0() { return cPrioritySTRINGTerminalRuleCall_15_0; }
		
		//SEMICOLON
		public RuleCall getSEMICOLONTerminalRuleCall_16() { return cSEMICOLONTerminalRuleCall_16; }
		
		//private=BOOL
		public Assignment getPrivateAssignment_17() { return cPrivateAssignment_17; }
		
		//BOOL
		public RuleCall getPrivateBOOLParserRuleCall_17_0() { return cPrivateBOOLParserRuleCall_17_0; }
		
		//SEMICOLON
		public RuleCall getSEMICOLONTerminalRuleCall_18() { return cSEMICOLONTerminalRuleCall_18; }
		
		//progress=INT
		public Assignment getProgressAssignment_19() { return cProgressAssignment_19; }
		
		//INT
		public RuleCall getProgressINTTerminalRuleCall_19_0() { return cProgressINTTerminalRuleCall_19_0; }
		
		//SEMICOLON
		public RuleCall getSEMICOLONTerminalRuleCall_20() { return cSEMICOLONTerminalRuleCall_20; }
		
		//Task+=Status
		public Assignment getTaskAssignment_21() { return cTaskAssignment_21; }
		
		//Status
		public RuleCall getTaskStatusParserRuleCall_21_0() { return cTaskStatusParserRuleCall_21_0; }
		
		//SEMICOLON
		public RuleCall getSEMICOLONTerminalRuleCall_22() { return cSEMICOLONTerminalRuleCall_22; }
		
		//assignedTo=CADENA
		public Assignment getAssignedToAssignment_23() { return cAssignedToAssignment_23; }
		
		//CADENA
		public RuleCall getAssignedToCADENATerminalRuleCall_23_0() { return cAssignedToCADENATerminalRuleCall_23_0; }
		
		//SEMICOLON
		public RuleCall getSEMICOLONTerminalRuleCall_24() { return cSEMICOLONTerminalRuleCall_24; }
		
		//createdDate=DATEHOUR
		public Assignment getCreatedDateAssignment_25() { return cCreatedDateAssignment_25; }
		
		//DATEHOUR
		public RuleCall getCreatedDateDATEHOURTerminalRuleCall_25_0() { return cCreatedDateDATEHOURTerminalRuleCall_25_0; }
		
		//SEMICOLON
		public RuleCall getSEMICOLONTerminalRuleCall_26() { return cSEMICOLONTerminalRuleCall_26; }
		
		//CADENA
		public RuleCall getCADENATerminalRuleCall_27() { return cCADENATerminalRuleCall_27; }
		
		////Created By Firstname
		//SEMICOLON
		public RuleCall getSEMICOLONTerminalRuleCall_28() { return cSEMICOLONTerminalRuleCall_28; }
		
		//CADENA
		public RuleCall getCADENATerminalRuleCall_29() { return cCADENATerminalRuleCall_29; }
		
		//// Created By Lastname
		//SEMICOLON
		public RuleCall getSEMICOLONTerminalRuleCall_30() { return cSEMICOLONTerminalRuleCall_30; }
		
		//completedDate=DATEHOUR
		public Assignment getCompletedDateAssignment_31() { return cCompletedDateAssignment_31; }
		
		//DATEHOUR
		public RuleCall getCompletedDateDATEHOURTerminalRuleCall_31_0() { return cCompletedDateDATEHOURTerminalRuleCall_31_0; }
		
		//SEMICOLON
		public RuleCall getSEMICOLONTerminalRuleCall_32() { return cSEMICOLONTerminalRuleCall_32; }
		
		//CADENA
		public RuleCall getCADENATerminalRuleCall_33() { return cCADENATerminalRuleCall_33; }
		
		////Completed By Firstname
		//SEMICOLON
		public RuleCall getSEMICOLONTerminalRuleCall_34() { return cSEMICOLONTerminalRuleCall_34; }
		
		//CADENA
		public RuleCall getCADENATerminalRuleCall_35() { return cCADENATerminalRuleCall_35; }
		
		////Completed By Lastname
		//SEMICOLON
		public RuleCall getSEMICOLONTerminalRuleCall_36() { return cSEMICOLONTerminalRuleCall_36; }
		
		//timeLogged=INT?
		public Assignment getTimeLoggedAssignment_37() { return cTimeLoggedAssignment_37; }
		
		//INT
		public RuleCall getTimeLoggedINTTerminalRuleCall_37_0() { return cTimeLoggedINTTerminalRuleCall_37_0; }
		
		//SEMICOLON
		public RuleCall getSEMICOLONTerminalRuleCall_38() { return cSEMICOLONTerminalRuleCall_38; }
		
		//billableMinutes=INT?
		public Assignment getBillableMinutesAssignment_39() { return cBillableMinutesAssignment_39; }
		
		//INT
		public RuleCall getBillableMinutesINTTerminalRuleCall_39_0() { return cBillableMinutesINTTerminalRuleCall_39_0; }
		
		//SEMICOLON
		public RuleCall getSEMICOLONTerminalRuleCall_40() { return cSEMICOLONTerminalRuleCall_40; }
		
		//parentTask=[Task]?
		public Assignment getParentTaskAssignment_41() { return cParentTaskAssignment_41; }
		
		//[Task]
		public CrossReference getParentTaskTaskCrossReference_41_0() { return cParentTaskTaskCrossReference_41_0; }
		
		//ID
		public RuleCall getParentTaskTaskIDTerminalRuleCall_41_0_1() { return cParentTaskTaskIDTerminalRuleCall_41_0_1; }
		
		//SEMICOLON
		public RuleCall getSEMICOLONTerminalRuleCall_42() { return cSEMICOLONTerminalRuleCall_42; }
		
		//completedOnTime=BOOL
		public Assignment getCompletedOnTimeAssignment_43() { return cCompletedOnTimeAssignment_43; }
		
		//BOOL
		public RuleCall getCompletedOnTimeBOOLParserRuleCall_43_0() { return cCompletedOnTimeBOOLParserRuleCall_43_0; }
		
		//SEMICOLON
		public RuleCall getSEMICOLONTerminalRuleCall_44() { return cSEMICOLONTerminalRuleCall_44; }
		
		//timeEstimated=INT
		public Assignment getTimeEstimatedAssignment_45() { return cTimeEstimatedAssignment_45; }
		
		//INT
		public RuleCall getTimeEstimatedINTTerminalRuleCall_45_0() { return cTimeEstimatedINTTerminalRuleCall_45_0; }
		
		//SEMICOLON
		public RuleCall getSEMICOLONTerminalRuleCall_46() { return cSEMICOLONTerminalRuleCall_46; }
		
		//tags=CADENA?
		public Assignment getTagsAssignment_47() { return cTagsAssignment_47; }
		
		//CADENA
		public RuleCall getTagsCADENATerminalRuleCall_47_0() { return cTagsCADENATerminalRuleCall_47_0; }
		
		//NEWLINE
		public RuleCall getNEWLINETerminalRuleCall_48() { return cNEWLINETerminalRuleCall_48; }
	}
	public class StatusElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "co.edu.uniandes.KPIGenerator.Status");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cStatusNameAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final Alternatives cStatusNameAlternatives_0_0 = (Alternatives)cStatusNameAssignment_0.eContents().get(0);
		private final Keyword cStatusNameCompletedKeyword_0_0_0 = (Keyword)cStatusNameAlternatives_0_0.eContents().get(0);
		private final Keyword cStatusNameNewKeyword_0_0_1 = (Keyword)cStatusNameAlternatives_0_0.eContents().get(1);
		private final RuleCall cSEMICOLONTerminalRuleCall_1 = (RuleCall)cGroup.eContents().get(1);
		private final Assignment cTextAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cTextCADENATerminalRuleCall_2_0 = (RuleCall)cTextAssignment_2.eContents().get(0);
		
		//Status:
		//	statusName=('completed' | 'new') SEMICOLON
		//	text=CADENA;
		@Override public ParserRule getRule() { return rule; }
		
		//statusName=('completed' | 'new') SEMICOLON text=CADENA
		public Group getGroup() { return cGroup; }
		
		//statusName=('completed' | 'new')
		public Assignment getStatusNameAssignment_0() { return cStatusNameAssignment_0; }
		
		//('completed' | 'new')
		public Alternatives getStatusNameAlternatives_0_0() { return cStatusNameAlternatives_0_0; }
		
		//'completed'
		public Keyword getStatusNameCompletedKeyword_0_0_0() { return cStatusNameCompletedKeyword_0_0_0; }
		
		//'new'
		public Keyword getStatusNameNewKeyword_0_0_1() { return cStatusNameNewKeyword_0_0_1; }
		
		//SEMICOLON
		public RuleCall getSEMICOLONTerminalRuleCall_1() { return cSEMICOLONTerminalRuleCall_1; }
		
		//text=CADENA
		public Assignment getTextAssignment_2() { return cTextAssignment_2; }
		
		//CADENA
		public RuleCall getTextCADENATerminalRuleCall_2_0() { return cTextCADENATerminalRuleCall_2_0; }
	}
	public class BOOLElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "co.edu.uniandes.KPIGenerator.BOOL");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cBOOLAction_0 = (Action)cGroup.eContents().get(0);
		private final Alternatives cAlternatives_1 = (Alternatives)cGroup.eContents().get(1);
		private final Keyword cFALSOKeyword_1_0 = (Keyword)cAlternatives_1.eContents().get(0);
		private final Keyword cVERDADEROKeyword_1_1 = (Keyword)cAlternatives_1.eContents().get(1);
		
		//BOOL:
		//	{BOOL} ('FALSO' | 'VERDADERO');
		@Override public ParserRule getRule() { return rule; }
		
		//{BOOL} ('FALSO' | 'VERDADERO')
		public Group getGroup() { return cGroup; }
		
		//{BOOL}
		public Action getBOOLAction_0() { return cBOOLAction_0; }
		
		//('FALSO' | 'VERDADERO')
		public Alternatives getAlternatives_1() { return cAlternatives_1; }
		
		//'FALSO'
		public Keyword getFALSOKeyword_1_0() { return cFALSOKeyword_1_0; }
		
		//'VERDADERO'
		public Keyword getVERDADEROKeyword_1_1() { return cVERDADEROKeyword_1_1; }
	}
	
	
	private final TaskElements pTask;
	private final StatusElements pStatus;
	private final BOOLElements pBOOL;
	private final TerminalRule tSEMICOLON;
	private final TerminalRule tNEWLINE;
	private final TerminalRule tCADENA;
	private final TerminalRule tDATEHOUR;
	private final TerminalRule tDATE;
	
	private final Grammar grammar;
	
	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public KPIGeneratorGrammarAccess(GrammarProvider grammarProvider,
			TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pTask = new TaskElements();
		this.pStatus = new StatusElements();
		this.pBOOL = new BOOLElements();
		this.tSEMICOLON = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "co.edu.uniandes.KPIGenerator.SEMICOLON");
		this.tNEWLINE = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "co.edu.uniandes.KPIGenerator.NEWLINE");
		this.tCADENA = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "co.edu.uniandes.KPIGenerator.CADENA");
		this.tDATEHOUR = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "co.edu.uniandes.KPIGenerator.DATEHOUR");
		this.tDATE = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "co.edu.uniandes.KPIGenerator.DATE");
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("co.edu.uniandes.KPIGenerator".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	
	
	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//Task:
	//	{Task} id=INT
	//	SEMICOLON
	//	project=CADENA
	//	SEMICOLON
	//	milestone=CADENA?
	//	SEMICOLON
	//	name=CADENA
	//	SEMICOLON
	//	TaskDescription=CADENA?
	//	SEMICOLON
	//	startDate=DATE
	//	SEMICOLON
	//	DueDate=DATE
	//	SEMICOLON
	//	priority=STRING?
	//	SEMICOLON
	//	private=BOOL
	//	SEMICOLON
	//	progress=INT
	//	SEMICOLON
	//	Task+=Status
	//	SEMICOLON
	//	assignedTo=CADENA
	//	SEMICOLON
	//	createdDate=DATEHOUR
	//	SEMICOLON
	//	CADENA //Created By Firstname
	//	SEMICOLON
	//	CADENA // Created By Lastname
	//	SEMICOLON
	//	completedDate=DATEHOUR
	//	SEMICOLON
	//	CADENA //Completed By Firstname
	//	SEMICOLON
	//	CADENA //Completed By Lastname
	//	SEMICOLON
	//	timeLogged=INT?
	//	SEMICOLON
	//	billableMinutes=INT?
	//	SEMICOLON
	//	parentTask=[Task]?
	//	SEMICOLON
	//	completedOnTime=BOOL
	//	SEMICOLON
	//	timeEstimated=INT
	//	SEMICOLON
	//	tags=CADENA?
	//	NEWLINE;
	public TaskElements getTaskAccess() {
		return pTask;
	}
	
	public ParserRule getTaskRule() {
		return getTaskAccess().getRule();
	}
	
	//Status:
	//	statusName=('completed' | 'new') SEMICOLON
	//	text=CADENA;
	public StatusElements getStatusAccess() {
		return pStatus;
	}
	
	public ParserRule getStatusRule() {
		return getStatusAccess().getRule();
	}
	
	//BOOL:
	//	{BOOL} ('FALSO' | 'VERDADERO');
	public BOOLElements getBOOLAccess() {
		return pBOOL;
	}
	
	public ParserRule getBOOLRule() {
		return getBOOLAccess().getRule();
	}
	
	//terminal SEMICOLON:
	//	';';
	public TerminalRule getSEMICOLONRule() {
		return tSEMICOLON;
	}
	
	//terminal NEWLINE:
	//	'\n' | EOF;
	public TerminalRule getNEWLINERule() {
		return tNEWLINE;
	}
	
	//terminal CADENA:
	//	('a'..'z' | 'A'..'Z' | 'Á' | 'á' | 'É' | 'é' | 'Í' | 'í' | 'Ó' | 'ó' | 'Ú' | 'ú' | '-' | ' ' | '|' | '.')+
	//	'0'..'9'*+;
	public TerminalRule getCADENARule() {
		return tCADENA;
	}
	
	//terminal DATEHOUR: //28/07/2016 10:17 PM
	//	'0'..'9' '0'..'9' '/' '0'..'9' '0'..'9' '/' '0'..'9' '0'..'9' '0'..'9' '0'..'9' ' ' '0'..'9' '0'..'9' ':' '0'..'9'
	//	'0'..'9' ' ' ('AM' | 'PM');
	public TerminalRule getDATEHOURRule() {
		return tDATEHOUR;
	}
	
	//terminal DATE: //28/07/2016
	//	'0'..'9' '0'..'9' '/' '0'..'9' '0'..'9' '/' '0'..'9' '0'..'9' '0'..'9' '0'..'9';
	public TerminalRule getDATERule() {
		return tDATE;
	}
	
	//terminal ID:
	//	'^'? ('a'..'z' | 'A'..'Z' | '_') ('a'..'z' | 'A'..'Z' | '_' | '0'..'9')*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	}
	
	//terminal INT returns ecore::EInt:
	//	'0'..'9'+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	}
	
	//terminal STRING:
	//	'"' ('\\' . | !('\\' | '"'))* '"' | "'" ('\\' . | !('\\' | "'"))* "'";
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	}
	
	//terminal ML_COMMENT:
	//	'/ *'->'* /';
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	}
	
	//terminal SL_COMMENT:
	//	'//' !('\n' | '\r')* ('\r'? '\n')?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	}
	
	//terminal WS:
	//	' ' | '\t' | '\r' | '\n'+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	}
	
	//terminal ANY_OTHER:
	//	.;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	}
}
