/*
 * generated by Xtext 2.10.0
 */
package co.edu.uniandes.ui;

import com.google.inject.Injector;
import kpigrammar.ui.internal.KpigrammarActivator;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class KPIGeneratorExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return KpigrammarActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return KpigrammarActivator.getInstance().getInjector(KpigrammarActivator.CO_EDU_UNIANDES_KPIGENERATOR);
	}
	
}
