/**
 * generated by Xtext 2.10.0
 */
package co.edu.uniandes.kPIGenerator;

import org.eclipse.emf.ecore.EFactory;

/**
 * <!-- begin-user-doc -->
 * The <b>Factory</b> for the model.
 * It provides a create method for each non-abstract class of the model.
 * <!-- end-user-doc -->
 * @see co.edu.uniandes.kPIGenerator.KPIGeneratorPackage
 * @generated
 */
public interface KPIGeneratorFactory extends EFactory
{
  /**
   * The singleton instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  KPIGeneratorFactory eINSTANCE = co.edu.uniandes.kPIGenerator.impl.KPIGeneratorFactoryImpl.init();

  /**
   * Returns a new object of class '<em>Task</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Task</em>'.
   * @generated
   */
  Task createTask();

  /**
   * Returns a new object of class '<em>Status</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Status</em>'.
   * @generated
   */
  Status createStatus();

  /**
   * Returns a new object of class '<em>BOOL</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>BOOL</em>'.
   * @generated
   */
  BOOL createBOOL();

  /**
   * Returns a new object of class '<em>Task Name</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Task Name</em>'.
   * @generated
   */
  TaskName createTaskName();

  /**
   * Returns the package supported by this factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the package supported by this factory.
   * @generated
   */
  KPIGeneratorPackage getKPIGeneratorPackage();

} //KPIGeneratorFactory
