/**
 * generated by Xtext 2.10.0
 */
package co.edu.uniandes.kPIGenerator;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see co.edu.uniandes.kPIGenerator.KPIGeneratorFactory
 * @model kind="package"
 * @generated
 */
public interface KPIGeneratorPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "kPIGenerator";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.edu.co/uniandes/KPIGenerator";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "kPIGenerator";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  KPIGeneratorPackage eINSTANCE = co.edu.uniandes.kPIGenerator.impl.KPIGeneratorPackageImpl.init();

  /**
   * The meta object id for the '{@link co.edu.uniandes.kPIGenerator.impl.TaskImpl <em>Task</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see co.edu.uniandes.kPIGenerator.impl.TaskImpl
   * @see co.edu.uniandes.kPIGenerator.impl.KPIGeneratorPackageImpl#getTask()
   * @generated
   */
  int TASK = 0;

  /**
   * The feature id for the '<em><b>Task Id</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TASK__TASK_ID = 0;

  /**
   * The feature id for the '<em><b>Task List</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TASK__TASK_LIST = 1;

  /**
   * The feature id for the '<em><b>Milestone</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TASK__MILESTONE = 2;

  /**
   * The feature id for the '<em><b>Task</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TASK__TASK = 3;

  /**
   * The feature id for the '<em><b>Task Description</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TASK__TASK_DESCRIPTION = 4;

  /**
   * The feature id for the '<em><b>Start Date</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TASK__START_DATE = 5;

  /**
   * The feature id for the '<em><b>Due Date</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TASK__DUE_DATE = 6;

  /**
   * The feature id for the '<em><b>Priority</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TASK__PRIORITY = 7;

  /**
   * The feature id for the '<em><b>Private</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TASK__PRIVATE = 8;

  /**
   * The feature id for the '<em><b>Progress</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TASK__PROGRESS = 9;

  /**
   * The feature id for the '<em><b>Assigned To</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TASK__ASSIGNED_TO = 10;

  /**
   * The feature id for the '<em><b>Created Date</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TASK__CREATED_DATE = 11;

  /**
   * The feature id for the '<em><b>Completed Date</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TASK__COMPLETED_DATE = 12;

  /**
   * The feature id for the '<em><b>Time Logged</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TASK__TIME_LOGGED = 13;

  /**
   * The feature id for the '<em><b>Billable Minutes</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TASK__BILLABLE_MINUTES = 14;

  /**
   * The feature id for the '<em><b>Task Parent</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TASK__TASK_PARENT = 15;

  /**
   * The feature id for the '<em><b>Completed On Time</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TASK__COMPLETED_ON_TIME = 16;

  /**
   * The feature id for the '<em><b>Time Estimated</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TASK__TIME_ESTIMATED = 17;

  /**
   * The feature id for the '<em><b>Tags</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TASK__TAGS = 18;

  /**
   * The number of structural features of the '<em>Task</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TASK_FEATURE_COUNT = 19;

  /**
   * The meta object id for the '{@link co.edu.uniandes.kPIGenerator.impl.StatusImpl <em>Status</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see co.edu.uniandes.kPIGenerator.impl.StatusImpl
   * @see co.edu.uniandes.kPIGenerator.impl.KPIGeneratorPackageImpl#getStatus()
   * @generated
   */
  int STATUS = 1;

  /**
   * The feature id for the '<em><b>Status Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STATUS__STATUS_NAME = 0;

  /**
   * The feature id for the '<em><b>Text</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STATUS__TEXT = 1;

  /**
   * The number of structural features of the '<em>Status</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STATUS_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link co.edu.uniandes.kPIGenerator.impl.BOOLImpl <em>BOOL</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see co.edu.uniandes.kPIGenerator.impl.BOOLImpl
   * @see co.edu.uniandes.kPIGenerator.impl.KPIGeneratorPackageImpl#getBOOL()
   * @generated
   */
  int BOOL = 2;

  /**
   * The number of structural features of the '<em>BOOL</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BOOL_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link co.edu.uniandes.kPIGenerator.impl.TaskNameImpl <em>Task Name</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see co.edu.uniandes.kPIGenerator.impl.TaskNameImpl
   * @see co.edu.uniandes.kPIGenerator.impl.KPIGeneratorPackageImpl#getTaskName()
   * @generated
   */
  int TASK_NAME = 3;

  /**
   * The feature id for the '<em><b>Phase</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TASK_NAME__PHASE = 0;

  /**
   * The feature id for the '<em><b>Subphase</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TASK_NAME__SUBPHASE = 1;

  /**
   * The feature id for the '<em><b>Use Case</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TASK_NAME__USE_CASE = 2;

  /**
   * The feature id for the '<em><b>Version</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TASK_NAME__VERSION = 3;

  /**
   * The number of structural features of the '<em>Task Name</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TASK_NAME_FEATURE_COUNT = 4;


  /**
   * Returns the meta object for class '{@link co.edu.uniandes.kPIGenerator.Task <em>Task</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Task</em>'.
   * @see co.edu.uniandes.kPIGenerator.Task
   * @generated
   */
  EClass getTask();

  /**
   * Returns the meta object for the attribute '{@link co.edu.uniandes.kPIGenerator.Task#getTaskId <em>Task Id</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Task Id</em>'.
   * @see co.edu.uniandes.kPIGenerator.Task#getTaskId()
   * @see #getTask()
   * @generated
   */
  EAttribute getTask_TaskId();

  /**
   * Returns the meta object for the attribute '{@link co.edu.uniandes.kPIGenerator.Task#getTaskList <em>Task List</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Task List</em>'.
   * @see co.edu.uniandes.kPIGenerator.Task#getTaskList()
   * @see #getTask()
   * @generated
   */
  EAttribute getTask_TaskList();

  /**
   * Returns the meta object for the attribute '{@link co.edu.uniandes.kPIGenerator.Task#getMilestone <em>Milestone</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Milestone</em>'.
   * @see co.edu.uniandes.kPIGenerator.Task#getMilestone()
   * @see #getTask()
   * @generated
   */
  EAttribute getTask_Milestone();

  /**
   * Returns the meta object for the containment reference list '{@link co.edu.uniandes.kPIGenerator.Task#getTask <em>Task</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Task</em>'.
   * @see co.edu.uniandes.kPIGenerator.Task#getTask()
   * @see #getTask()
   * @generated
   */
  EReference getTask_Task();

  /**
   * Returns the meta object for the attribute '{@link co.edu.uniandes.kPIGenerator.Task#getTaskDescription <em>Task Description</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Task Description</em>'.
   * @see co.edu.uniandes.kPIGenerator.Task#getTaskDescription()
   * @see #getTask()
   * @generated
   */
  EAttribute getTask_TaskDescription();

  /**
   * Returns the meta object for the attribute '{@link co.edu.uniandes.kPIGenerator.Task#getStartDate <em>Start Date</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Start Date</em>'.
   * @see co.edu.uniandes.kPIGenerator.Task#getStartDate()
   * @see #getTask()
   * @generated
   */
  EAttribute getTask_StartDate();

  /**
   * Returns the meta object for the attribute '{@link co.edu.uniandes.kPIGenerator.Task#getDueDate <em>Due Date</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Due Date</em>'.
   * @see co.edu.uniandes.kPIGenerator.Task#getDueDate()
   * @see #getTask()
   * @generated
   */
  EAttribute getTask_DueDate();

  /**
   * Returns the meta object for the attribute '{@link co.edu.uniandes.kPIGenerator.Task#getPriority <em>Priority</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Priority</em>'.
   * @see co.edu.uniandes.kPIGenerator.Task#getPriority()
   * @see #getTask()
   * @generated
   */
  EAttribute getTask_Priority();

  /**
   * Returns the meta object for the containment reference '{@link co.edu.uniandes.kPIGenerator.Task#getPrivate <em>Private</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Private</em>'.
   * @see co.edu.uniandes.kPIGenerator.Task#getPrivate()
   * @see #getTask()
   * @generated
   */
  EReference getTask_Private();

  /**
   * Returns the meta object for the attribute '{@link co.edu.uniandes.kPIGenerator.Task#getProgress <em>Progress</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Progress</em>'.
   * @see co.edu.uniandes.kPIGenerator.Task#getProgress()
   * @see #getTask()
   * @generated
   */
  EAttribute getTask_Progress();

  /**
   * Returns the meta object for the attribute '{@link co.edu.uniandes.kPIGenerator.Task#getAssignedTo <em>Assigned To</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Assigned To</em>'.
   * @see co.edu.uniandes.kPIGenerator.Task#getAssignedTo()
   * @see #getTask()
   * @generated
   */
  EAttribute getTask_AssignedTo();

  /**
   * Returns the meta object for the attribute '{@link co.edu.uniandes.kPIGenerator.Task#getCreatedDate <em>Created Date</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Created Date</em>'.
   * @see co.edu.uniandes.kPIGenerator.Task#getCreatedDate()
   * @see #getTask()
   * @generated
   */
  EAttribute getTask_CreatedDate();

  /**
   * Returns the meta object for the attribute '{@link co.edu.uniandes.kPIGenerator.Task#getCompletedDate <em>Completed Date</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Completed Date</em>'.
   * @see co.edu.uniandes.kPIGenerator.Task#getCompletedDate()
   * @see #getTask()
   * @generated
   */
  EAttribute getTask_CompletedDate();

  /**
   * Returns the meta object for the attribute '{@link co.edu.uniandes.kPIGenerator.Task#getTimeLogged <em>Time Logged</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Time Logged</em>'.
   * @see co.edu.uniandes.kPIGenerator.Task#getTimeLogged()
   * @see #getTask()
   * @generated
   */
  EAttribute getTask_TimeLogged();

  /**
   * Returns the meta object for the attribute '{@link co.edu.uniandes.kPIGenerator.Task#getBillableMinutes <em>Billable Minutes</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Billable Minutes</em>'.
   * @see co.edu.uniandes.kPIGenerator.Task#getBillableMinutes()
   * @see #getTask()
   * @generated
   */
  EAttribute getTask_BillableMinutes();

  /**
   * Returns the meta object for the attribute '{@link co.edu.uniandes.kPIGenerator.Task#getTaskParent <em>Task Parent</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Task Parent</em>'.
   * @see co.edu.uniandes.kPIGenerator.Task#getTaskParent()
   * @see #getTask()
   * @generated
   */
  EAttribute getTask_TaskParent();

  /**
   * Returns the meta object for the containment reference '{@link co.edu.uniandes.kPIGenerator.Task#getCompletedOnTime <em>Completed On Time</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Completed On Time</em>'.
   * @see co.edu.uniandes.kPIGenerator.Task#getCompletedOnTime()
   * @see #getTask()
   * @generated
   */
  EReference getTask_CompletedOnTime();

  /**
   * Returns the meta object for the attribute '{@link co.edu.uniandes.kPIGenerator.Task#getTimeEstimated <em>Time Estimated</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Time Estimated</em>'.
   * @see co.edu.uniandes.kPIGenerator.Task#getTimeEstimated()
   * @see #getTask()
   * @generated
   */
  EAttribute getTask_TimeEstimated();

  /**
   * Returns the meta object for the attribute '{@link co.edu.uniandes.kPIGenerator.Task#getTags <em>Tags</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Tags</em>'.
   * @see co.edu.uniandes.kPIGenerator.Task#getTags()
   * @see #getTask()
   * @generated
   */
  EAttribute getTask_Tags();

  /**
   * Returns the meta object for class '{@link co.edu.uniandes.kPIGenerator.Status <em>Status</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Status</em>'.
   * @see co.edu.uniandes.kPIGenerator.Status
   * @generated
   */
  EClass getStatus();

  /**
   * Returns the meta object for the attribute '{@link co.edu.uniandes.kPIGenerator.Status#getStatusName <em>Status Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Status Name</em>'.
   * @see co.edu.uniandes.kPIGenerator.Status#getStatusName()
   * @see #getStatus()
   * @generated
   */
  EAttribute getStatus_StatusName();

  /**
   * Returns the meta object for the attribute '{@link co.edu.uniandes.kPIGenerator.Status#getText <em>Text</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Text</em>'.
   * @see co.edu.uniandes.kPIGenerator.Status#getText()
   * @see #getStatus()
   * @generated
   */
  EAttribute getStatus_Text();

  /**
   * Returns the meta object for class '{@link co.edu.uniandes.kPIGenerator.BOOL <em>BOOL</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>BOOL</em>'.
   * @see co.edu.uniandes.kPIGenerator.BOOL
   * @generated
   */
  EClass getBOOL();

  /**
   * Returns the meta object for class '{@link co.edu.uniandes.kPIGenerator.TaskName <em>Task Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Task Name</em>'.
   * @see co.edu.uniandes.kPIGenerator.TaskName
   * @generated
   */
  EClass getTaskName();

  /**
   * Returns the meta object for the attribute '{@link co.edu.uniandes.kPIGenerator.TaskName#getPhase <em>Phase</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Phase</em>'.
   * @see co.edu.uniandes.kPIGenerator.TaskName#getPhase()
   * @see #getTaskName()
   * @generated
   */
  EAttribute getTaskName_Phase();

  /**
   * Returns the meta object for the attribute '{@link co.edu.uniandes.kPIGenerator.TaskName#getSubphase <em>Subphase</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Subphase</em>'.
   * @see co.edu.uniandes.kPIGenerator.TaskName#getSubphase()
   * @see #getTaskName()
   * @generated
   */
  EAttribute getTaskName_Subphase();

  /**
   * Returns the meta object for the attribute '{@link co.edu.uniandes.kPIGenerator.TaskName#getUseCase <em>Use Case</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Use Case</em>'.
   * @see co.edu.uniandes.kPIGenerator.TaskName#getUseCase()
   * @see #getTaskName()
   * @generated
   */
  EAttribute getTaskName_UseCase();

  /**
   * Returns the meta object for the attribute '{@link co.edu.uniandes.kPIGenerator.TaskName#getVersion <em>Version</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Version</em>'.
   * @see co.edu.uniandes.kPIGenerator.TaskName#getVersion()
   * @see #getTaskName()
   * @generated
   */
  EAttribute getTaskName_Version();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  KPIGeneratorFactory getKPIGeneratorFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link co.edu.uniandes.kPIGenerator.impl.TaskImpl <em>Task</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see co.edu.uniandes.kPIGenerator.impl.TaskImpl
     * @see co.edu.uniandes.kPIGenerator.impl.KPIGeneratorPackageImpl#getTask()
     * @generated
     */
    EClass TASK = eINSTANCE.getTask();

    /**
     * The meta object literal for the '<em><b>Task Id</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TASK__TASK_ID = eINSTANCE.getTask_TaskId();

    /**
     * The meta object literal for the '<em><b>Task List</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TASK__TASK_LIST = eINSTANCE.getTask_TaskList();

    /**
     * The meta object literal for the '<em><b>Milestone</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TASK__MILESTONE = eINSTANCE.getTask_Milestone();

    /**
     * The meta object literal for the '<em><b>Task</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TASK__TASK = eINSTANCE.getTask_Task();

    /**
     * The meta object literal for the '<em><b>Task Description</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TASK__TASK_DESCRIPTION = eINSTANCE.getTask_TaskDescription();

    /**
     * The meta object literal for the '<em><b>Start Date</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TASK__START_DATE = eINSTANCE.getTask_StartDate();

    /**
     * The meta object literal for the '<em><b>Due Date</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TASK__DUE_DATE = eINSTANCE.getTask_DueDate();

    /**
     * The meta object literal for the '<em><b>Priority</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TASK__PRIORITY = eINSTANCE.getTask_Priority();

    /**
     * The meta object literal for the '<em><b>Private</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TASK__PRIVATE = eINSTANCE.getTask_Private();

    /**
     * The meta object literal for the '<em><b>Progress</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TASK__PROGRESS = eINSTANCE.getTask_Progress();

    /**
     * The meta object literal for the '<em><b>Assigned To</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TASK__ASSIGNED_TO = eINSTANCE.getTask_AssignedTo();

    /**
     * The meta object literal for the '<em><b>Created Date</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TASK__CREATED_DATE = eINSTANCE.getTask_CreatedDate();

    /**
     * The meta object literal for the '<em><b>Completed Date</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TASK__COMPLETED_DATE = eINSTANCE.getTask_CompletedDate();

    /**
     * The meta object literal for the '<em><b>Time Logged</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TASK__TIME_LOGGED = eINSTANCE.getTask_TimeLogged();

    /**
     * The meta object literal for the '<em><b>Billable Minutes</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TASK__BILLABLE_MINUTES = eINSTANCE.getTask_BillableMinutes();

    /**
     * The meta object literal for the '<em><b>Task Parent</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TASK__TASK_PARENT = eINSTANCE.getTask_TaskParent();

    /**
     * The meta object literal for the '<em><b>Completed On Time</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TASK__COMPLETED_ON_TIME = eINSTANCE.getTask_CompletedOnTime();

    /**
     * The meta object literal for the '<em><b>Time Estimated</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TASK__TIME_ESTIMATED = eINSTANCE.getTask_TimeEstimated();

    /**
     * The meta object literal for the '<em><b>Tags</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TASK__TAGS = eINSTANCE.getTask_Tags();

    /**
     * The meta object literal for the '{@link co.edu.uniandes.kPIGenerator.impl.StatusImpl <em>Status</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see co.edu.uniandes.kPIGenerator.impl.StatusImpl
     * @see co.edu.uniandes.kPIGenerator.impl.KPIGeneratorPackageImpl#getStatus()
     * @generated
     */
    EClass STATUS = eINSTANCE.getStatus();

    /**
     * The meta object literal for the '<em><b>Status Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute STATUS__STATUS_NAME = eINSTANCE.getStatus_StatusName();

    /**
     * The meta object literal for the '<em><b>Text</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute STATUS__TEXT = eINSTANCE.getStatus_Text();

    /**
     * The meta object literal for the '{@link co.edu.uniandes.kPIGenerator.impl.BOOLImpl <em>BOOL</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see co.edu.uniandes.kPIGenerator.impl.BOOLImpl
     * @see co.edu.uniandes.kPIGenerator.impl.KPIGeneratorPackageImpl#getBOOL()
     * @generated
     */
    EClass BOOL = eINSTANCE.getBOOL();

    /**
     * The meta object literal for the '{@link co.edu.uniandes.kPIGenerator.impl.TaskNameImpl <em>Task Name</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see co.edu.uniandes.kPIGenerator.impl.TaskNameImpl
     * @see co.edu.uniandes.kPIGenerator.impl.KPIGeneratorPackageImpl#getTaskName()
     * @generated
     */
    EClass TASK_NAME = eINSTANCE.getTaskName();

    /**
     * The meta object literal for the '<em><b>Phase</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TASK_NAME__PHASE = eINSTANCE.getTaskName_Phase();

    /**
     * The meta object literal for the '<em><b>Subphase</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TASK_NAME__SUBPHASE = eINSTANCE.getTaskName_Subphase();

    /**
     * The meta object literal for the '<em><b>Use Case</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TASK_NAME__USE_CASE = eINSTANCE.getTaskName_UseCase();

    /**
     * The meta object literal for the '<em><b>Version</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TASK_NAME__VERSION = eINSTANCE.getTaskName_Version();

  }

} //KPIGeneratorPackage
