/*
 * generated by Xtext 2.10.0
 */
package co.edu.uniandes.ui.tests;

import com.google.inject.Injector;
import kpigrammar.ui.internal.KpigrammarActivator;
import org.eclipse.xtext.junit4.IInjectorProvider;

public class KPIGeneratorUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return KpigrammarActivator.getInstance().getInjector("co.edu.uniandes.KPIGenerator");
	}

}
