/**
 * generated by Xtext 2.10.0
 */
package co.edu.uniandes.kPIGenerator.impl;

import co.edu.uniandes.kPIGenerator.BOOL;
import co.edu.uniandes.kPIGenerator.KPIGeneratorPackage;
import co.edu.uniandes.kPIGenerator.Project;
import co.edu.uniandes.kPIGenerator.Status;
import co.edu.uniandes.kPIGenerator.Task;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Task</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link co.edu.uniandes.kPIGenerator.impl.TaskImpl#getProject <em>Project</em>}</li>
 *   <li>{@link co.edu.uniandes.kPIGenerator.impl.TaskImpl#getMilestone <em>Milestone</em>}</li>
 *   <li>{@link co.edu.uniandes.kPIGenerator.impl.TaskImpl#getName <em>Name</em>}</li>
 *   <li>{@link co.edu.uniandes.kPIGenerator.impl.TaskImpl#getTaskDescription <em>Task Description</em>}</li>
 *   <li>{@link co.edu.uniandes.kPIGenerator.impl.TaskImpl#getStartDate <em>Start Date</em>}</li>
 *   <li>{@link co.edu.uniandes.kPIGenerator.impl.TaskImpl#getDueDate <em>Due Date</em>}</li>
 *   <li>{@link co.edu.uniandes.kPIGenerator.impl.TaskImpl#getPriority <em>Priority</em>}</li>
 *   <li>{@link co.edu.uniandes.kPIGenerator.impl.TaskImpl#getPrivate <em>Private</em>}</li>
 *   <li>{@link co.edu.uniandes.kPIGenerator.impl.TaskImpl#getProgress <em>Progress</em>}</li>
 *   <li>{@link co.edu.uniandes.kPIGenerator.impl.TaskImpl#getStatus <em>Status</em>}</li>
 *   <li>{@link co.edu.uniandes.kPIGenerator.impl.TaskImpl#getAssignedTo <em>Assigned To</em>}</li>
 *   <li>{@link co.edu.uniandes.kPIGenerator.impl.TaskImpl#getCreatedDate <em>Created Date</em>}</li>
 *   <li>{@link co.edu.uniandes.kPIGenerator.impl.TaskImpl#getCreatedHour <em>Created Hour</em>}</li>
 *   <li>{@link co.edu.uniandes.kPIGenerator.impl.TaskImpl#getCompletedDate <em>Completed Date</em>}</li>
 *   <li>{@link co.edu.uniandes.kPIGenerator.impl.TaskImpl#getCompletedHour <em>Completed Hour</em>}</li>
 *   <li>{@link co.edu.uniandes.kPIGenerator.impl.TaskImpl#getTimeLogged <em>Time Logged</em>}</li>
 *   <li>{@link co.edu.uniandes.kPIGenerator.impl.TaskImpl#getBillableMinutes <em>Billable Minutes</em>}</li>
 *   <li>{@link co.edu.uniandes.kPIGenerator.impl.TaskImpl#getParentTask <em>Parent Task</em>}</li>
 *   <li>{@link co.edu.uniandes.kPIGenerator.impl.TaskImpl#getCompletedOnTime <em>Completed On Time</em>}</li>
 *   <li>{@link co.edu.uniandes.kPIGenerator.impl.TaskImpl#getTimeEstimated <em>Time Estimated</em>}</li>
 *   <li>{@link co.edu.uniandes.kPIGenerator.impl.TaskImpl#getTags <em>Tags</em>}</li>
 * </ul>
 *
 * @generated
 */
public class TaskImpl extends MinimalEObjectImpl.Container implements Task
{
  /**
   * The cached value of the '{@link #getProject() <em>Project</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getProject()
   * @generated
   * @ordered
   */
  protected Project project;

  /**
   * The default value of the '{@link #getMilestone() <em>Milestone</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getMilestone()
   * @generated
   * @ordered
   */
  protected static final String MILESTONE_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getMilestone() <em>Milestone</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getMilestone()
   * @generated
   * @ordered
   */
  protected String milestone = MILESTONE_EDEFAULT;

  /**
   * The default value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected static final String NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected String name = NAME_EDEFAULT;

  /**
   * The default value of the '{@link #getTaskDescription() <em>Task Description</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTaskDescription()
   * @generated
   * @ordered
   */
  protected static final String TASK_DESCRIPTION_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getTaskDescription() <em>Task Description</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTaskDescription()
   * @generated
   * @ordered
   */
  protected String taskDescription = TASK_DESCRIPTION_EDEFAULT;

  /**
   * The default value of the '{@link #getStartDate() <em>Start Date</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getStartDate()
   * @generated
   * @ordered
   */
  protected static final String START_DATE_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getStartDate() <em>Start Date</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getStartDate()
   * @generated
   * @ordered
   */
  protected String startDate = START_DATE_EDEFAULT;

  /**
   * The default value of the '{@link #getDueDate() <em>Due Date</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDueDate()
   * @generated
   * @ordered
   */
  protected static final String DUE_DATE_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getDueDate() <em>Due Date</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDueDate()
   * @generated
   * @ordered
   */
  protected String dueDate = DUE_DATE_EDEFAULT;

  /**
   * The default value of the '{@link #getPriority() <em>Priority</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPriority()
   * @generated
   * @ordered
   */
  protected static final String PRIORITY_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getPriority() <em>Priority</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPriority()
   * @generated
   * @ordered
   */
  protected String priority = PRIORITY_EDEFAULT;

  /**
   * The cached value of the '{@link #getPrivate() <em>Private</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPrivate()
   * @generated
   * @ordered
   */
  protected BOOL private_;

  /**
   * The default value of the '{@link #getProgress() <em>Progress</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getProgress()
   * @generated
   * @ordered
   */
  protected static final int PROGRESS_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getProgress() <em>Progress</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getProgress()
   * @generated
   * @ordered
   */
  protected int progress = PROGRESS_EDEFAULT;

  /**
   * The cached value of the '{@link #getStatus() <em>Status</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getStatus()
   * @generated
   * @ordered
   */
  protected Status status;

  /**
   * The default value of the '{@link #getAssignedTo() <em>Assigned To</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getAssignedTo()
   * @generated
   * @ordered
   */
  protected static final String ASSIGNED_TO_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getAssignedTo() <em>Assigned To</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getAssignedTo()
   * @generated
   * @ordered
   */
  protected String assignedTo = ASSIGNED_TO_EDEFAULT;

  /**
   * The default value of the '{@link #getCreatedDate() <em>Created Date</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCreatedDate()
   * @generated
   * @ordered
   */
  protected static final String CREATED_DATE_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getCreatedDate() <em>Created Date</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCreatedDate()
   * @generated
   * @ordered
   */
  protected String createdDate = CREATED_DATE_EDEFAULT;

  /**
   * The default value of the '{@link #getCreatedHour() <em>Created Hour</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCreatedHour()
   * @generated
   * @ordered
   */
  protected static final String CREATED_HOUR_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getCreatedHour() <em>Created Hour</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCreatedHour()
   * @generated
   * @ordered
   */
  protected String createdHour = CREATED_HOUR_EDEFAULT;

  /**
   * The default value of the '{@link #getCompletedDate() <em>Completed Date</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCompletedDate()
   * @generated
   * @ordered
   */
  protected static final String COMPLETED_DATE_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getCompletedDate() <em>Completed Date</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCompletedDate()
   * @generated
   * @ordered
   */
  protected String completedDate = COMPLETED_DATE_EDEFAULT;

  /**
   * The default value of the '{@link #getCompletedHour() <em>Completed Hour</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCompletedHour()
   * @generated
   * @ordered
   */
  protected static final String COMPLETED_HOUR_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getCompletedHour() <em>Completed Hour</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCompletedHour()
   * @generated
   * @ordered
   */
  protected String completedHour = COMPLETED_HOUR_EDEFAULT;

  /**
   * The default value of the '{@link #getTimeLogged() <em>Time Logged</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTimeLogged()
   * @generated
   * @ordered
   */
  protected static final int TIME_LOGGED_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getTimeLogged() <em>Time Logged</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTimeLogged()
   * @generated
   * @ordered
   */
  protected int timeLogged = TIME_LOGGED_EDEFAULT;

  /**
   * The default value of the '{@link #getBillableMinutes() <em>Billable Minutes</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getBillableMinutes()
   * @generated
   * @ordered
   */
  protected static final int BILLABLE_MINUTES_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getBillableMinutes() <em>Billable Minutes</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getBillableMinutes()
   * @generated
   * @ordered
   */
  protected int billableMinutes = BILLABLE_MINUTES_EDEFAULT;

  /**
   * The cached value of the '{@link #getParentTask() <em>Parent Task</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getParentTask()
   * @generated
   * @ordered
   */
  protected Task parentTask;

  /**
   * The cached value of the '{@link #getCompletedOnTime() <em>Completed On Time</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCompletedOnTime()
   * @generated
   * @ordered
   */
  protected BOOL completedOnTime;

  /**
   * The default value of the '{@link #getTimeEstimated() <em>Time Estimated</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTimeEstimated()
   * @generated
   * @ordered
   */
  protected static final int TIME_ESTIMATED_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getTimeEstimated() <em>Time Estimated</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTimeEstimated()
   * @generated
   * @ordered
   */
  protected int timeEstimated = TIME_ESTIMATED_EDEFAULT;

  /**
   * The default value of the '{@link #getTags() <em>Tags</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTags()
   * @generated
   * @ordered
   */
  protected static final String TAGS_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getTags() <em>Tags</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTags()
   * @generated
   * @ordered
   */
  protected String tags = TAGS_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected TaskImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return KPIGeneratorPackage.Literals.TASK;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Project getProject()
  {
    return project;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetProject(Project newProject, NotificationChain msgs)
  {
    Project oldProject = project;
    project = newProject;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, KPIGeneratorPackage.TASK__PROJECT, oldProject, newProject);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setProject(Project newProject)
  {
    if (newProject != project)
    {
      NotificationChain msgs = null;
      if (project != null)
        msgs = ((InternalEObject)project).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - KPIGeneratorPackage.TASK__PROJECT, null, msgs);
      if (newProject != null)
        msgs = ((InternalEObject)newProject).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - KPIGeneratorPackage.TASK__PROJECT, null, msgs);
      msgs = basicSetProject(newProject, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, KPIGeneratorPackage.TASK__PROJECT, newProject, newProject));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getMilestone()
  {
    return milestone;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setMilestone(String newMilestone)
  {
    String oldMilestone = milestone;
    milestone = newMilestone;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, KPIGeneratorPackage.TASK__MILESTONE, oldMilestone, milestone));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setName(String newName)
  {
    String oldName = name;
    name = newName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, KPIGeneratorPackage.TASK__NAME, oldName, name));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getTaskDescription()
  {
    return taskDescription;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setTaskDescription(String newTaskDescription)
  {
    String oldTaskDescription = taskDescription;
    taskDescription = newTaskDescription;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, KPIGeneratorPackage.TASK__TASK_DESCRIPTION, oldTaskDescription, taskDescription));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getStartDate()
  {
    return startDate;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setStartDate(String newStartDate)
  {
    String oldStartDate = startDate;
    startDate = newStartDate;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, KPIGeneratorPackage.TASK__START_DATE, oldStartDate, startDate));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getDueDate()
  {
    return dueDate;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setDueDate(String newDueDate)
  {
    String oldDueDate = dueDate;
    dueDate = newDueDate;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, KPIGeneratorPackage.TASK__DUE_DATE, oldDueDate, dueDate));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getPriority()
  {
    return priority;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setPriority(String newPriority)
  {
    String oldPriority = priority;
    priority = newPriority;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, KPIGeneratorPackage.TASK__PRIORITY, oldPriority, priority));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public BOOL getPrivate()
  {
    return private_;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetPrivate(BOOL newPrivate, NotificationChain msgs)
  {
    BOOL oldPrivate = private_;
    private_ = newPrivate;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, KPIGeneratorPackage.TASK__PRIVATE, oldPrivate, newPrivate);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setPrivate(BOOL newPrivate)
  {
    if (newPrivate != private_)
    {
      NotificationChain msgs = null;
      if (private_ != null)
        msgs = ((InternalEObject)private_).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - KPIGeneratorPackage.TASK__PRIVATE, null, msgs);
      if (newPrivate != null)
        msgs = ((InternalEObject)newPrivate).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - KPIGeneratorPackage.TASK__PRIVATE, null, msgs);
      msgs = basicSetPrivate(newPrivate, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, KPIGeneratorPackage.TASK__PRIVATE, newPrivate, newPrivate));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public int getProgress()
  {
    return progress;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setProgress(int newProgress)
  {
    int oldProgress = progress;
    progress = newProgress;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, KPIGeneratorPackage.TASK__PROGRESS, oldProgress, progress));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Status getStatus()
  {
    return status;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetStatus(Status newStatus, NotificationChain msgs)
  {
    Status oldStatus = status;
    status = newStatus;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, KPIGeneratorPackage.TASK__STATUS, oldStatus, newStatus);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setStatus(Status newStatus)
  {
    if (newStatus != status)
    {
      NotificationChain msgs = null;
      if (status != null)
        msgs = ((InternalEObject)status).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - KPIGeneratorPackage.TASK__STATUS, null, msgs);
      if (newStatus != null)
        msgs = ((InternalEObject)newStatus).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - KPIGeneratorPackage.TASK__STATUS, null, msgs);
      msgs = basicSetStatus(newStatus, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, KPIGeneratorPackage.TASK__STATUS, newStatus, newStatus));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getAssignedTo()
  {
    return assignedTo;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setAssignedTo(String newAssignedTo)
  {
    String oldAssignedTo = assignedTo;
    assignedTo = newAssignedTo;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, KPIGeneratorPackage.TASK__ASSIGNED_TO, oldAssignedTo, assignedTo));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getCreatedDate()
  {
    return createdDate;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setCreatedDate(String newCreatedDate)
  {
    String oldCreatedDate = createdDate;
    createdDate = newCreatedDate;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, KPIGeneratorPackage.TASK__CREATED_DATE, oldCreatedDate, createdDate));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getCreatedHour()
  {
    return createdHour;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setCreatedHour(String newCreatedHour)
  {
    String oldCreatedHour = createdHour;
    createdHour = newCreatedHour;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, KPIGeneratorPackage.TASK__CREATED_HOUR, oldCreatedHour, createdHour));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getCompletedDate()
  {
    return completedDate;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setCompletedDate(String newCompletedDate)
  {
    String oldCompletedDate = completedDate;
    completedDate = newCompletedDate;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, KPIGeneratorPackage.TASK__COMPLETED_DATE, oldCompletedDate, completedDate));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getCompletedHour()
  {
    return completedHour;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setCompletedHour(String newCompletedHour)
  {
    String oldCompletedHour = completedHour;
    completedHour = newCompletedHour;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, KPIGeneratorPackage.TASK__COMPLETED_HOUR, oldCompletedHour, completedHour));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public int getTimeLogged()
  {
    return timeLogged;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setTimeLogged(int newTimeLogged)
  {
    int oldTimeLogged = timeLogged;
    timeLogged = newTimeLogged;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, KPIGeneratorPackage.TASK__TIME_LOGGED, oldTimeLogged, timeLogged));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public int getBillableMinutes()
  {
    return billableMinutes;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setBillableMinutes(int newBillableMinutes)
  {
    int oldBillableMinutes = billableMinutes;
    billableMinutes = newBillableMinutes;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, KPIGeneratorPackage.TASK__BILLABLE_MINUTES, oldBillableMinutes, billableMinutes));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Task getParentTask()
  {
    if (parentTask != null && parentTask.eIsProxy())
    {
      InternalEObject oldParentTask = (InternalEObject)parentTask;
      parentTask = (Task)eResolveProxy(oldParentTask);
      if (parentTask != oldParentTask)
      {
        if (eNotificationRequired())
          eNotify(new ENotificationImpl(this, Notification.RESOLVE, KPIGeneratorPackage.TASK__PARENT_TASK, oldParentTask, parentTask));
      }
    }
    return parentTask;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Task basicGetParentTask()
  {
    return parentTask;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setParentTask(Task newParentTask)
  {
    Task oldParentTask = parentTask;
    parentTask = newParentTask;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, KPIGeneratorPackage.TASK__PARENT_TASK, oldParentTask, parentTask));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public BOOL getCompletedOnTime()
  {
    return completedOnTime;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetCompletedOnTime(BOOL newCompletedOnTime, NotificationChain msgs)
  {
    BOOL oldCompletedOnTime = completedOnTime;
    completedOnTime = newCompletedOnTime;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, KPIGeneratorPackage.TASK__COMPLETED_ON_TIME, oldCompletedOnTime, newCompletedOnTime);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setCompletedOnTime(BOOL newCompletedOnTime)
  {
    if (newCompletedOnTime != completedOnTime)
    {
      NotificationChain msgs = null;
      if (completedOnTime != null)
        msgs = ((InternalEObject)completedOnTime).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - KPIGeneratorPackage.TASK__COMPLETED_ON_TIME, null, msgs);
      if (newCompletedOnTime != null)
        msgs = ((InternalEObject)newCompletedOnTime).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - KPIGeneratorPackage.TASK__COMPLETED_ON_TIME, null, msgs);
      msgs = basicSetCompletedOnTime(newCompletedOnTime, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, KPIGeneratorPackage.TASK__COMPLETED_ON_TIME, newCompletedOnTime, newCompletedOnTime));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public int getTimeEstimated()
  {
    return timeEstimated;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setTimeEstimated(int newTimeEstimated)
  {
    int oldTimeEstimated = timeEstimated;
    timeEstimated = newTimeEstimated;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, KPIGeneratorPackage.TASK__TIME_ESTIMATED, oldTimeEstimated, timeEstimated));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getTags()
  {
    return tags;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setTags(String newTags)
  {
    String oldTags = tags;
    tags = newTags;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, KPIGeneratorPackage.TASK__TAGS, oldTags, tags));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case KPIGeneratorPackage.TASK__PROJECT:
        return basicSetProject(null, msgs);
      case KPIGeneratorPackage.TASK__PRIVATE:
        return basicSetPrivate(null, msgs);
      case KPIGeneratorPackage.TASK__STATUS:
        return basicSetStatus(null, msgs);
      case KPIGeneratorPackage.TASK__COMPLETED_ON_TIME:
        return basicSetCompletedOnTime(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case KPIGeneratorPackage.TASK__PROJECT:
        return getProject();
      case KPIGeneratorPackage.TASK__MILESTONE:
        return getMilestone();
      case KPIGeneratorPackage.TASK__NAME:
        return getName();
      case KPIGeneratorPackage.TASK__TASK_DESCRIPTION:
        return getTaskDescription();
      case KPIGeneratorPackage.TASK__START_DATE:
        return getStartDate();
      case KPIGeneratorPackage.TASK__DUE_DATE:
        return getDueDate();
      case KPIGeneratorPackage.TASK__PRIORITY:
        return getPriority();
      case KPIGeneratorPackage.TASK__PRIVATE:
        return getPrivate();
      case KPIGeneratorPackage.TASK__PROGRESS:
        return getProgress();
      case KPIGeneratorPackage.TASK__STATUS:
        return getStatus();
      case KPIGeneratorPackage.TASK__ASSIGNED_TO:
        return getAssignedTo();
      case KPIGeneratorPackage.TASK__CREATED_DATE:
        return getCreatedDate();
      case KPIGeneratorPackage.TASK__CREATED_HOUR:
        return getCreatedHour();
      case KPIGeneratorPackage.TASK__COMPLETED_DATE:
        return getCompletedDate();
      case KPIGeneratorPackage.TASK__COMPLETED_HOUR:
        return getCompletedHour();
      case KPIGeneratorPackage.TASK__TIME_LOGGED:
        return getTimeLogged();
      case KPIGeneratorPackage.TASK__BILLABLE_MINUTES:
        return getBillableMinutes();
      case KPIGeneratorPackage.TASK__PARENT_TASK:
        if (resolve) return getParentTask();
        return basicGetParentTask();
      case KPIGeneratorPackage.TASK__COMPLETED_ON_TIME:
        return getCompletedOnTime();
      case KPIGeneratorPackage.TASK__TIME_ESTIMATED:
        return getTimeEstimated();
      case KPIGeneratorPackage.TASK__TAGS:
        return getTags();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case KPIGeneratorPackage.TASK__PROJECT:
        setProject((Project)newValue);
        return;
      case KPIGeneratorPackage.TASK__MILESTONE:
        setMilestone((String)newValue);
        return;
      case KPIGeneratorPackage.TASK__NAME:
        setName((String)newValue);
        return;
      case KPIGeneratorPackage.TASK__TASK_DESCRIPTION:
        setTaskDescription((String)newValue);
        return;
      case KPIGeneratorPackage.TASK__START_DATE:
        setStartDate((String)newValue);
        return;
      case KPIGeneratorPackage.TASK__DUE_DATE:
        setDueDate((String)newValue);
        return;
      case KPIGeneratorPackage.TASK__PRIORITY:
        setPriority((String)newValue);
        return;
      case KPIGeneratorPackage.TASK__PRIVATE:
        setPrivate((BOOL)newValue);
        return;
      case KPIGeneratorPackage.TASK__PROGRESS:
        setProgress((Integer)newValue);
        return;
      case KPIGeneratorPackage.TASK__STATUS:
        setStatus((Status)newValue);
        return;
      case KPIGeneratorPackage.TASK__ASSIGNED_TO:
        setAssignedTo((String)newValue);
        return;
      case KPIGeneratorPackage.TASK__CREATED_DATE:
        setCreatedDate((String)newValue);
        return;
      case KPIGeneratorPackage.TASK__CREATED_HOUR:
        setCreatedHour((String)newValue);
        return;
      case KPIGeneratorPackage.TASK__COMPLETED_DATE:
        setCompletedDate((String)newValue);
        return;
      case KPIGeneratorPackage.TASK__COMPLETED_HOUR:
        setCompletedHour((String)newValue);
        return;
      case KPIGeneratorPackage.TASK__TIME_LOGGED:
        setTimeLogged((Integer)newValue);
        return;
      case KPIGeneratorPackage.TASK__BILLABLE_MINUTES:
        setBillableMinutes((Integer)newValue);
        return;
      case KPIGeneratorPackage.TASK__PARENT_TASK:
        setParentTask((Task)newValue);
        return;
      case KPIGeneratorPackage.TASK__COMPLETED_ON_TIME:
        setCompletedOnTime((BOOL)newValue);
        return;
      case KPIGeneratorPackage.TASK__TIME_ESTIMATED:
        setTimeEstimated((Integer)newValue);
        return;
      case KPIGeneratorPackage.TASK__TAGS:
        setTags((String)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case KPIGeneratorPackage.TASK__PROJECT:
        setProject((Project)null);
        return;
      case KPIGeneratorPackage.TASK__MILESTONE:
        setMilestone(MILESTONE_EDEFAULT);
        return;
      case KPIGeneratorPackage.TASK__NAME:
        setName(NAME_EDEFAULT);
        return;
      case KPIGeneratorPackage.TASK__TASK_DESCRIPTION:
        setTaskDescription(TASK_DESCRIPTION_EDEFAULT);
        return;
      case KPIGeneratorPackage.TASK__START_DATE:
        setStartDate(START_DATE_EDEFAULT);
        return;
      case KPIGeneratorPackage.TASK__DUE_DATE:
        setDueDate(DUE_DATE_EDEFAULT);
        return;
      case KPIGeneratorPackage.TASK__PRIORITY:
        setPriority(PRIORITY_EDEFAULT);
        return;
      case KPIGeneratorPackage.TASK__PRIVATE:
        setPrivate((BOOL)null);
        return;
      case KPIGeneratorPackage.TASK__PROGRESS:
        setProgress(PROGRESS_EDEFAULT);
        return;
      case KPIGeneratorPackage.TASK__STATUS:
        setStatus((Status)null);
        return;
      case KPIGeneratorPackage.TASK__ASSIGNED_TO:
        setAssignedTo(ASSIGNED_TO_EDEFAULT);
        return;
      case KPIGeneratorPackage.TASK__CREATED_DATE:
        setCreatedDate(CREATED_DATE_EDEFAULT);
        return;
      case KPIGeneratorPackage.TASK__CREATED_HOUR:
        setCreatedHour(CREATED_HOUR_EDEFAULT);
        return;
      case KPIGeneratorPackage.TASK__COMPLETED_DATE:
        setCompletedDate(COMPLETED_DATE_EDEFAULT);
        return;
      case KPIGeneratorPackage.TASK__COMPLETED_HOUR:
        setCompletedHour(COMPLETED_HOUR_EDEFAULT);
        return;
      case KPIGeneratorPackage.TASK__TIME_LOGGED:
        setTimeLogged(TIME_LOGGED_EDEFAULT);
        return;
      case KPIGeneratorPackage.TASK__BILLABLE_MINUTES:
        setBillableMinutes(BILLABLE_MINUTES_EDEFAULT);
        return;
      case KPIGeneratorPackage.TASK__PARENT_TASK:
        setParentTask((Task)null);
        return;
      case KPIGeneratorPackage.TASK__COMPLETED_ON_TIME:
        setCompletedOnTime((BOOL)null);
        return;
      case KPIGeneratorPackage.TASK__TIME_ESTIMATED:
        setTimeEstimated(TIME_ESTIMATED_EDEFAULT);
        return;
      case KPIGeneratorPackage.TASK__TAGS:
        setTags(TAGS_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case KPIGeneratorPackage.TASK__PROJECT:
        return project != null;
      case KPIGeneratorPackage.TASK__MILESTONE:
        return MILESTONE_EDEFAULT == null ? milestone != null : !MILESTONE_EDEFAULT.equals(milestone);
      case KPIGeneratorPackage.TASK__NAME:
        return NAME_EDEFAULT == null ? name != null : !NAME_EDEFAULT.equals(name);
      case KPIGeneratorPackage.TASK__TASK_DESCRIPTION:
        return TASK_DESCRIPTION_EDEFAULT == null ? taskDescription != null : !TASK_DESCRIPTION_EDEFAULT.equals(taskDescription);
      case KPIGeneratorPackage.TASK__START_DATE:
        return START_DATE_EDEFAULT == null ? startDate != null : !START_DATE_EDEFAULT.equals(startDate);
      case KPIGeneratorPackage.TASK__DUE_DATE:
        return DUE_DATE_EDEFAULT == null ? dueDate != null : !DUE_DATE_EDEFAULT.equals(dueDate);
      case KPIGeneratorPackage.TASK__PRIORITY:
        return PRIORITY_EDEFAULT == null ? priority != null : !PRIORITY_EDEFAULT.equals(priority);
      case KPIGeneratorPackage.TASK__PRIVATE:
        return private_ != null;
      case KPIGeneratorPackage.TASK__PROGRESS:
        return progress != PROGRESS_EDEFAULT;
      case KPIGeneratorPackage.TASK__STATUS:
        return status != null;
      case KPIGeneratorPackage.TASK__ASSIGNED_TO:
        return ASSIGNED_TO_EDEFAULT == null ? assignedTo != null : !ASSIGNED_TO_EDEFAULT.equals(assignedTo);
      case KPIGeneratorPackage.TASK__CREATED_DATE:
        return CREATED_DATE_EDEFAULT == null ? createdDate != null : !CREATED_DATE_EDEFAULT.equals(createdDate);
      case KPIGeneratorPackage.TASK__CREATED_HOUR:
        return CREATED_HOUR_EDEFAULT == null ? createdHour != null : !CREATED_HOUR_EDEFAULT.equals(createdHour);
      case KPIGeneratorPackage.TASK__COMPLETED_DATE:
        return COMPLETED_DATE_EDEFAULT == null ? completedDate != null : !COMPLETED_DATE_EDEFAULT.equals(completedDate);
      case KPIGeneratorPackage.TASK__COMPLETED_HOUR:
        return COMPLETED_HOUR_EDEFAULT == null ? completedHour != null : !COMPLETED_HOUR_EDEFAULT.equals(completedHour);
      case KPIGeneratorPackage.TASK__TIME_LOGGED:
        return timeLogged != TIME_LOGGED_EDEFAULT;
      case KPIGeneratorPackage.TASK__BILLABLE_MINUTES:
        return billableMinutes != BILLABLE_MINUTES_EDEFAULT;
      case KPIGeneratorPackage.TASK__PARENT_TASK:
        return parentTask != null;
      case KPIGeneratorPackage.TASK__COMPLETED_ON_TIME:
        return completedOnTime != null;
      case KPIGeneratorPackage.TASK__TIME_ESTIMATED:
        return timeEstimated != TIME_ESTIMATED_EDEFAULT;
      case KPIGeneratorPackage.TASK__TAGS:
        return TAGS_EDEFAULT == null ? tags != null : !TAGS_EDEFAULT.equals(tags);
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuffer result = new StringBuffer(super.toString());
    result.append(" (milestone: ");
    result.append(milestone);
    result.append(", name: ");
    result.append(name);
    result.append(", TaskDescription: ");
    result.append(taskDescription);
    result.append(", startDate: ");
    result.append(startDate);
    result.append(", DueDate: ");
    result.append(dueDate);
    result.append(", priority: ");
    result.append(priority);
    result.append(", progress: ");
    result.append(progress);
    result.append(", assignedTo: ");
    result.append(assignedTo);
    result.append(", createdDate: ");
    result.append(createdDate);
    result.append(", createdHour: ");
    result.append(createdHour);
    result.append(", completedDate: ");
    result.append(completedDate);
    result.append(", completedHour: ");
    result.append(completedHour);
    result.append(", timeLogged: ");
    result.append(timeLogged);
    result.append(", billableMinutes: ");
    result.append(billableMinutes);
    result.append(", timeEstimated: ");
    result.append(timeEstimated);
    result.append(", tags: ");
    result.append(tags);
    result.append(')');
    return result.toString();
  }

} //TaskImpl
