/*
 * generated by Xtext 2.10.0
 */
package co.edu.uniandes.services;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.List;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Alternatives;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.Grammar;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.Group;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.common.services.TerminalsGrammarAccess;
import org.eclipse.xtext.service.AbstractElementFinder.AbstractGrammarElementFinder;
import org.eclipse.xtext.service.GrammarProvider;

@Singleton
public class KPIGeneratorGrammarAccess extends AbstractGrammarElementFinder {
	
	public class RootElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "co.edu.uniandes.KPIGenerator.Root");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cLeftSquareBracketKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cProjectsAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cProjectsProjectParserRuleCall_1_0 = (RuleCall)cProjectsAssignment_1.eContents().get(0);
		private final Group cGroup_2 = (Group)cGroup.eContents().get(2);
		private final Keyword cCommaKeyword_2_0 = (Keyword)cGroup_2.eContents().get(0);
		private final Assignment cProjectsAssignment_2_1 = (Assignment)cGroup_2.eContents().get(1);
		private final RuleCall cProjectsProjectParserRuleCall_2_1_0 = (RuleCall)cProjectsAssignment_2_1.eContents().get(0);
		private final Keyword cRightSquareBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		
		//Root:
		//	'[' projects+=Project (',' projects+=Project)* ']';
		@Override public ParserRule getRule() { return rule; }
		
		//'[' projects+=Project (',' projects+=Project)* ']'
		public Group getGroup() { return cGroup; }
		
		//'['
		public Keyword getLeftSquareBracketKeyword_0() { return cLeftSquareBracketKeyword_0; }
		
		//projects+=Project
		public Assignment getProjectsAssignment_1() { return cProjectsAssignment_1; }
		
		//Project
		public RuleCall getProjectsProjectParserRuleCall_1_0() { return cProjectsProjectParserRuleCall_1_0; }
		
		//(',' projects+=Project)*
		public Group getGroup_2() { return cGroup_2; }
		
		//','
		public Keyword getCommaKeyword_2_0() { return cCommaKeyword_2_0; }
		
		//projects+=Project
		public Assignment getProjectsAssignment_2_1() { return cProjectsAssignment_2_1; }
		
		//Project
		public RuleCall getProjectsProjectParserRuleCall_2_1_0() { return cProjectsProjectParserRuleCall_2_1_0; }
		
		//']'
		public Keyword getRightSquareBracketKeyword_3() { return cRightSquareBracketKeyword_3; }
	}
	public class ProjectElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "co.edu.uniandes.KPIGenerator.Project");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cProjectAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cNameKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cProjectNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cProjectNameCADENATerminalRuleCall_2_0 = (RuleCall)cProjectNameAssignment_2.eContents().get(0);
		private final Keyword cPhasesKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cPhasesAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cPhasesPhaseParserRuleCall_4_0 = (RuleCall)cPhasesAssignment_4.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cCommaKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cPhasesAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final RuleCall cPhasesPhaseParserRuleCall_5_1_0 = (RuleCall)cPhasesAssignment_5_1.eContents().get(0);
		private final Keyword cRightSquareBracketRightCurlyBracketKeyword_6 = (Keyword)cGroup.eContents().get(6);
		
		//Project:
		//	{Project}
		//	'{"name":"' projectName=CADENA '","phases":[' phases+=Phase (',' phases+=Phase)* ']}';
		@Override public ParserRule getRule() { return rule; }
		
		//{Project} '{"name":"' projectName=CADENA '","phases":[' phases+=Phase (',' phases+=Phase)* ']}'
		public Group getGroup() { return cGroup; }
		
		//{Project}
		public Action getProjectAction_0() { return cProjectAction_0; }
		
		//'{"name":"'
		public Keyword getNameKeyword_1() { return cNameKeyword_1; }
		
		//projectName=CADENA
		public Assignment getProjectNameAssignment_2() { return cProjectNameAssignment_2; }
		
		//CADENA
		public RuleCall getProjectNameCADENATerminalRuleCall_2_0() { return cProjectNameCADENATerminalRuleCall_2_0; }
		
		//'","phases":['
		public Keyword getPhasesKeyword_3() { return cPhasesKeyword_3; }
		
		//phases+=Phase
		public Assignment getPhasesAssignment_4() { return cPhasesAssignment_4; }
		
		//Phase
		public RuleCall getPhasesPhaseParserRuleCall_4_0() { return cPhasesPhaseParserRuleCall_4_0; }
		
		//(',' phases+=Phase)*
		public Group getGroup_5() { return cGroup_5; }
		
		//','
		public Keyword getCommaKeyword_5_0() { return cCommaKeyword_5_0; }
		
		//phases+=Phase
		public Assignment getPhasesAssignment_5_1() { return cPhasesAssignment_5_1; }
		
		//Phase
		public RuleCall getPhasesPhaseParserRuleCall_5_1_0() { return cPhasesPhaseParserRuleCall_5_1_0; }
		
		//']}'
		public Keyword getRightSquareBracketRightCurlyBracketKeyword_6() { return cRightSquareBracketRightCurlyBracketKeyword_6; }
	}
	public class PhaseElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "co.edu.uniandes.KPIGenerator.Phase");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cPhaseAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cCommaKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cNameKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cPhaseNameAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cPhaseNameCADENATerminalRuleCall_3_0 = (RuleCall)cPhaseNameAssignment_3.eContents().get(0);
		private final Keyword cTasksKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cTasksAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cTasksTaskParserRuleCall_5_0 = (RuleCall)cTasksAssignment_5.eContents().get(0);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cCommaKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Assignment cTasksAssignment_6_1 = (Assignment)cGroup_6.eContents().get(1);
		private final RuleCall cTasksTaskParserRuleCall_6_1_0 = (RuleCall)cTasksAssignment_6_1.eContents().get(0);
		private final Keyword cRightSquareBracketRightCurlyBracketKeyword_7 = (Keyword)cGroup.eContents().get(7);
		
		//Phase:
		//	{Phase} ','? '{"name":"' phaseName=CADENA '","tasks":[' tasks+=Task (',' tasks+=Task)* ']}';
		@Override public ParserRule getRule() { return rule; }
		
		//{Phase} ','? '{"name":"' phaseName=CADENA '","tasks":[' tasks+=Task (',' tasks+=Task)* ']}'
		public Group getGroup() { return cGroup; }
		
		//{Phase}
		public Action getPhaseAction_0() { return cPhaseAction_0; }
		
		//','?
		public Keyword getCommaKeyword_1() { return cCommaKeyword_1; }
		
		//'{"name":"'
		public Keyword getNameKeyword_2() { return cNameKeyword_2; }
		
		//phaseName=CADENA
		public Assignment getPhaseNameAssignment_3() { return cPhaseNameAssignment_3; }
		
		//CADENA
		public RuleCall getPhaseNameCADENATerminalRuleCall_3_0() { return cPhaseNameCADENATerminalRuleCall_3_0; }
		
		//'","tasks":['
		public Keyword getTasksKeyword_4() { return cTasksKeyword_4; }
		
		//tasks+=Task
		public Assignment getTasksAssignment_5() { return cTasksAssignment_5; }
		
		//Task
		public RuleCall getTasksTaskParserRuleCall_5_0() { return cTasksTaskParserRuleCall_5_0; }
		
		//(',' tasks+=Task)*
		public Group getGroup_6() { return cGroup_6; }
		
		//','
		public Keyword getCommaKeyword_6_0() { return cCommaKeyword_6_0; }
		
		//tasks+=Task
		public Assignment getTasksAssignment_6_1() { return cTasksAssignment_6_1; }
		
		//Task
		public RuleCall getTasksTaskParserRuleCall_6_1_0() { return cTasksTaskParserRuleCall_6_1_0; }
		
		//']}'
		public Keyword getRightSquareBracketRightCurlyBracketKeyword_7() { return cRightSquareBracketRightCurlyBracketKeyword_7; }
	}
	public class TaskElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "co.edu.uniandes.KPIGenerator.Task");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cTaskAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cIdKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cTaskIdAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cTaskIdINTTerminalRuleCall_2_0 = (RuleCall)cTaskIdAssignment_2.eContents().get(0);
		private final Keyword cNameKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cTaskNameAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cTaskNameCADENATerminalRuleCall_4_0 = (RuleCall)cTaskNameAssignment_4.eContents().get(0);
		private final Keyword cUseCaseKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Assignment cUseCaseAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final RuleCall cUseCaseCADENATerminalRuleCall_6_0 = (RuleCall)cUseCaseAssignment_6.eContents().get(0);
		private final Keyword cSequenceNumberKeyword_7 = (Keyword)cGroup.eContents().get(7);
		private final Assignment cSequenceNumberAssignment_8 = (Assignment)cGroup.eContents().get(8);
		private final RuleCall cSequenceNumberDOUBLETerminalRuleCall_8_0 = (RuleCall)cSequenceNumberAssignment_8.eContents().get(0);
		private final Keyword cStartDateKeyword_9 = (Keyword)cGroup.eContents().get(9);
		private final Assignment cStartDateAssignment_10 = (Assignment)cGroup.eContents().get(10);
		private final Alternatives cStartDateAlternatives_10_0 = (Alternatives)cStartDateAssignment_10.eContents().get(0);
		private final RuleCall cStartDateDATETerminalRuleCall_10_0_0 = (RuleCall)cStartDateAlternatives_10_0.eContents().get(0);
		private final Keyword cStartDateHyphenMinusKeyword_10_0_1 = (Keyword)cStartDateAlternatives_10_0.eContents().get(1);
		private final Keyword cDueDateKeyword_11 = (Keyword)cGroup.eContents().get(11);
		private final Assignment cDueDateAssignment_12 = (Assignment)cGroup.eContents().get(12);
		private final Alternatives cDueDateAlternatives_12_0 = (Alternatives)cDueDateAssignment_12.eContents().get(0);
		private final RuleCall cDueDateDATETerminalRuleCall_12_0_0 = (RuleCall)cDueDateAlternatives_12_0.eContents().get(0);
		private final Keyword cDueDateHyphenMinusKeyword_12_0_1 = (Keyword)cDueDateAlternatives_12_0.eContents().get(1);
		private final Keyword cIsPrivateKeyword_13 = (Keyword)cGroup.eContents().get(13);
		private final Assignment cIsPrivateAssignment_14 = (Assignment)cGroup.eContents().get(14);
		private final RuleCall cIsPrivateCADENATerminalRuleCall_14_0 = (RuleCall)cIsPrivateAssignment_14.eContents().get(0);
		private final Keyword cProgressKeyword_15 = (Keyword)cGroup.eContents().get(15);
		private final Assignment cProgressAssignment_16 = (Assignment)cGroup.eContents().get(16);
		private final RuleCall cProgressINTTerminalRuleCall_16_0 = (RuleCall)cProgressAssignment_16.eContents().get(0);
		private final Keyword cStatusKeyword_17 = (Keyword)cGroup.eContents().get(17);
		private final Assignment cStatusNameAssignment_18 = (Assignment)cGroup.eContents().get(18);
		private final RuleCall cStatusNameCADENATerminalRuleCall_18_0 = (RuleCall)cStatusNameAssignment_18.eContents().get(0);
		private final Keyword cStatusTextKeyword_19 = (Keyword)cGroup.eContents().get(19);
		private final Assignment cStatusTextAssignment_20 = (Assignment)cGroup.eContents().get(20);
		private final RuleCall cStatusTextCADENATerminalRuleCall_20_0 = (RuleCall)cStatusTextAssignment_20.eContents().get(0);
		private final Keyword cAssignedToKeyword_21 = (Keyword)cGroup.eContents().get(21);
		private final Assignment cAssignedToAssignment_22 = (Assignment)cGroup.eContents().get(22);
		private final RuleCall cAssignedToCADENATerminalRuleCall_22_0 = (RuleCall)cAssignedToAssignment_22.eContents().get(0);
		private final Keyword cCreatedDateKeyword_23 = (Keyword)cGroup.eContents().get(23);
		private final Assignment cCreatedDateAssignment_24 = (Assignment)cGroup.eContents().get(24);
		private final RuleCall cCreatedDateDATEHOURTerminalRuleCall_24_0 = (RuleCall)cCreatedDateAssignment_24.eContents().get(0);
		private final Keyword cCompletedDateKeyword_25 = (Keyword)cGroup.eContents().get(25);
		private final Assignment cCompletedDateAssignment_26 = (Assignment)cGroup.eContents().get(26);
		private final Alternatives cCompletedDateAlternatives_26_0 = (Alternatives)cCompletedDateAssignment_26.eContents().get(0);
		private final RuleCall cCompletedDateDATEHOURTerminalRuleCall_26_0_0 = (RuleCall)cCompletedDateAlternatives_26_0.eContents().get(0);
		private final Keyword cCompletedDateHyphenMinusKeyword_26_0_1 = (Keyword)cCompletedDateAlternatives_26_0.eContents().get(1);
		private final Keyword cTimeLoggedMinKeyword_27 = (Keyword)cGroup.eContents().get(27);
		private final Assignment cTimeLoggedMinAssignment_28 = (Assignment)cGroup.eContents().get(28);
		private final RuleCall cTimeLoggedMinINTTerminalRuleCall_28_0 = (RuleCall)cTimeLoggedMinAssignment_28.eContents().get(0);
		private final Keyword cBillableTimeKeyword_29 = (Keyword)cGroup.eContents().get(29);
		private final Assignment cBillableTimeAssignment_30 = (Assignment)cGroup.eContents().get(30);
		private final RuleCall cBillableTimeINTTerminalRuleCall_30_0 = (RuleCall)cBillableTimeAssignment_30.eContents().get(0);
		private final Keyword cCompletedOnTimeKeyword_31 = (Keyword)cGroup.eContents().get(31);
		private final Assignment cCompletedOnTimeAssignment_32 = (Assignment)cGroup.eContents().get(32);
		private final RuleCall cCompletedOnTimeCADENATerminalRuleCall_32_0 = (RuleCall)cCompletedOnTimeAssignment_32.eContents().get(0);
		private final Keyword cTimeEstimatedKeyword_33 = (Keyword)cGroup.eContents().get(33);
		private final Assignment cTimeEstimatedAssignment_34 = (Assignment)cGroup.eContents().get(34);
		private final RuleCall cTimeEstimatedINTTerminalRuleCall_34_0 = (RuleCall)cTimeEstimatedAssignment_34.eContents().get(0);
		private final Keyword cIsReprocessedTaskKeyword_35 = (Keyword)cGroup.eContents().get(35);
		private final Assignment cIsReprocessedTaskAssignment_36 = (Assignment)cGroup.eContents().get(36);
		private final RuleCall cIsReprocessedTaskCADENATerminalRuleCall_36_0 = (RuleCall)cIsReprocessedTaskAssignment_36.eContents().get(0);
		private final Keyword cIdParentTaskKeyword_37 = (Keyword)cGroup.eContents().get(37);
		private final Assignment cIdParentTaskAssignment_38 = (Assignment)cGroup.eContents().get(38);
		private final RuleCall cIdParentTaskINTTerminalRuleCall_38_0 = (RuleCall)cIdParentTaskAssignment_38.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_39 = (Keyword)cGroup.eContents().get(39);
		
		//Task:
		//	{Task}
		//	'{"id":' taskId=INT ',"name":"' taskName=CADENA '","useCase":"' useCase=CADENA '","sequenceNumber":'
		//	sequenceNumber=DOUBLE ',"startDate":"' startDate=(DATE | '-') '","dueDate":"' dueDate=(DATE | '-') '","isPrivate":'
		//	isPrivate=CADENA ',"progress":' progress=INT ',"status":"' statusName=CADENA '","statusText":"' statusText=CADENA
		//	'","assignedTo":"' assignedTo=CADENA '","createdDate":"' createdDate=DATEHOUR '","completedDate":"'
		//	completedDate=(DATEHOUR | '-') '","timeLoggedMin":' timeLoggedMin=INT ',"billableTime":' billableTime=INT
		//	',"completedOnTime":' completedOnTime=CADENA ',"timeEstimated":' timeEstimated=INT ',"isReprocessedTask":'
		//	isReprocessedTask=CADENA ',"idParentTask":' idParentTask=INT '}';
		@Override public ParserRule getRule() { return rule; }
		
		//{Task} '{"id":' taskId=INT ',"name":"' taskName=CADENA '","useCase":"' useCase=CADENA '","sequenceNumber":'
		//sequenceNumber=DOUBLE ',"startDate":"' startDate=(DATE | '-') '","dueDate":"' dueDate=(DATE | '-') '","isPrivate":'
		//isPrivate=CADENA ',"progress":' progress=INT ',"status":"' statusName=CADENA '","statusText":"' statusText=CADENA
		//'","assignedTo":"' assignedTo=CADENA '","createdDate":"' createdDate=DATEHOUR '","completedDate":"'
		//completedDate=(DATEHOUR | '-') '","timeLoggedMin":' timeLoggedMin=INT ',"billableTime":' billableTime=INT
		//',"completedOnTime":' completedOnTime=CADENA ',"timeEstimated":' timeEstimated=INT ',"isReprocessedTask":'
		//isReprocessedTask=CADENA ',"idParentTask":' idParentTask=INT '}'
		public Group getGroup() { return cGroup; }
		
		//{Task}
		public Action getTaskAction_0() { return cTaskAction_0; }
		
		//'{"id":'
		public Keyword getIdKeyword_1() { return cIdKeyword_1; }
		
		//taskId=INT
		public Assignment getTaskIdAssignment_2() { return cTaskIdAssignment_2; }
		
		//INT
		public RuleCall getTaskIdINTTerminalRuleCall_2_0() { return cTaskIdINTTerminalRuleCall_2_0; }
		
		//',"name":"'
		public Keyword getNameKeyword_3() { return cNameKeyword_3; }
		
		//taskName=CADENA
		public Assignment getTaskNameAssignment_4() { return cTaskNameAssignment_4; }
		
		//CADENA
		public RuleCall getTaskNameCADENATerminalRuleCall_4_0() { return cTaskNameCADENATerminalRuleCall_4_0; }
		
		//'","useCase":"'
		public Keyword getUseCaseKeyword_5() { return cUseCaseKeyword_5; }
		
		//useCase=CADENA
		public Assignment getUseCaseAssignment_6() { return cUseCaseAssignment_6; }
		
		//CADENA
		public RuleCall getUseCaseCADENATerminalRuleCall_6_0() { return cUseCaseCADENATerminalRuleCall_6_0; }
		
		//'","sequenceNumber":'
		public Keyword getSequenceNumberKeyword_7() { return cSequenceNumberKeyword_7; }
		
		//sequenceNumber=DOUBLE
		public Assignment getSequenceNumberAssignment_8() { return cSequenceNumberAssignment_8; }
		
		//DOUBLE
		public RuleCall getSequenceNumberDOUBLETerminalRuleCall_8_0() { return cSequenceNumberDOUBLETerminalRuleCall_8_0; }
		
		//',"startDate":"'
		public Keyword getStartDateKeyword_9() { return cStartDateKeyword_9; }
		
		//startDate=(DATE | '-')
		public Assignment getStartDateAssignment_10() { return cStartDateAssignment_10; }
		
		//(DATE | '-')
		public Alternatives getStartDateAlternatives_10_0() { return cStartDateAlternatives_10_0; }
		
		//DATE
		public RuleCall getStartDateDATETerminalRuleCall_10_0_0() { return cStartDateDATETerminalRuleCall_10_0_0; }
		
		//'-'
		public Keyword getStartDateHyphenMinusKeyword_10_0_1() { return cStartDateHyphenMinusKeyword_10_0_1; }
		
		//'","dueDate":"'
		public Keyword getDueDateKeyword_11() { return cDueDateKeyword_11; }
		
		//dueDate=(DATE | '-')
		public Assignment getDueDateAssignment_12() { return cDueDateAssignment_12; }
		
		//(DATE | '-')
		public Alternatives getDueDateAlternatives_12_0() { return cDueDateAlternatives_12_0; }
		
		//DATE
		public RuleCall getDueDateDATETerminalRuleCall_12_0_0() { return cDueDateDATETerminalRuleCall_12_0_0; }
		
		//'-'
		public Keyword getDueDateHyphenMinusKeyword_12_0_1() { return cDueDateHyphenMinusKeyword_12_0_1; }
		
		//'","isPrivate":'
		public Keyword getIsPrivateKeyword_13() { return cIsPrivateKeyword_13; }
		
		//isPrivate=CADENA
		public Assignment getIsPrivateAssignment_14() { return cIsPrivateAssignment_14; }
		
		//CADENA
		public RuleCall getIsPrivateCADENATerminalRuleCall_14_0() { return cIsPrivateCADENATerminalRuleCall_14_0; }
		
		//',"progress":'
		public Keyword getProgressKeyword_15() { return cProgressKeyword_15; }
		
		//progress=INT
		public Assignment getProgressAssignment_16() { return cProgressAssignment_16; }
		
		//INT
		public RuleCall getProgressINTTerminalRuleCall_16_0() { return cProgressINTTerminalRuleCall_16_0; }
		
		//',"status":"'
		public Keyword getStatusKeyword_17() { return cStatusKeyword_17; }
		
		//statusName=CADENA
		public Assignment getStatusNameAssignment_18() { return cStatusNameAssignment_18; }
		
		//CADENA
		public RuleCall getStatusNameCADENATerminalRuleCall_18_0() { return cStatusNameCADENATerminalRuleCall_18_0; }
		
		//'","statusText":"'
		public Keyword getStatusTextKeyword_19() { return cStatusTextKeyword_19; }
		
		//statusText=CADENA
		public Assignment getStatusTextAssignment_20() { return cStatusTextAssignment_20; }
		
		//CADENA
		public RuleCall getStatusTextCADENATerminalRuleCall_20_0() { return cStatusTextCADENATerminalRuleCall_20_0; }
		
		//'","assignedTo":"'
		public Keyword getAssignedToKeyword_21() { return cAssignedToKeyword_21; }
		
		//assignedTo=CADENA
		public Assignment getAssignedToAssignment_22() { return cAssignedToAssignment_22; }
		
		//CADENA
		public RuleCall getAssignedToCADENATerminalRuleCall_22_0() { return cAssignedToCADENATerminalRuleCall_22_0; }
		
		//'","createdDate":"'
		public Keyword getCreatedDateKeyword_23() { return cCreatedDateKeyword_23; }
		
		//createdDate=DATEHOUR
		public Assignment getCreatedDateAssignment_24() { return cCreatedDateAssignment_24; }
		
		//DATEHOUR
		public RuleCall getCreatedDateDATEHOURTerminalRuleCall_24_0() { return cCreatedDateDATEHOURTerminalRuleCall_24_0; }
		
		//'","completedDate":"'
		public Keyword getCompletedDateKeyword_25() { return cCompletedDateKeyword_25; }
		
		//completedDate=(DATEHOUR | '-')
		public Assignment getCompletedDateAssignment_26() { return cCompletedDateAssignment_26; }
		
		//(DATEHOUR | '-')
		public Alternatives getCompletedDateAlternatives_26_0() { return cCompletedDateAlternatives_26_0; }
		
		//DATEHOUR
		public RuleCall getCompletedDateDATEHOURTerminalRuleCall_26_0_0() { return cCompletedDateDATEHOURTerminalRuleCall_26_0_0; }
		
		//'-'
		public Keyword getCompletedDateHyphenMinusKeyword_26_0_1() { return cCompletedDateHyphenMinusKeyword_26_0_1; }
		
		//'","timeLoggedMin":'
		public Keyword getTimeLoggedMinKeyword_27() { return cTimeLoggedMinKeyword_27; }
		
		//timeLoggedMin=INT
		public Assignment getTimeLoggedMinAssignment_28() { return cTimeLoggedMinAssignment_28; }
		
		//INT
		public RuleCall getTimeLoggedMinINTTerminalRuleCall_28_0() { return cTimeLoggedMinINTTerminalRuleCall_28_0; }
		
		//',"billableTime":'
		public Keyword getBillableTimeKeyword_29() { return cBillableTimeKeyword_29; }
		
		//billableTime=INT
		public Assignment getBillableTimeAssignment_30() { return cBillableTimeAssignment_30; }
		
		//INT
		public RuleCall getBillableTimeINTTerminalRuleCall_30_0() { return cBillableTimeINTTerminalRuleCall_30_0; }
		
		//',"completedOnTime":'
		public Keyword getCompletedOnTimeKeyword_31() { return cCompletedOnTimeKeyword_31; }
		
		//completedOnTime=CADENA
		public Assignment getCompletedOnTimeAssignment_32() { return cCompletedOnTimeAssignment_32; }
		
		//CADENA
		public RuleCall getCompletedOnTimeCADENATerminalRuleCall_32_0() { return cCompletedOnTimeCADENATerminalRuleCall_32_0; }
		
		//',"timeEstimated":'
		public Keyword getTimeEstimatedKeyword_33() { return cTimeEstimatedKeyword_33; }
		
		//timeEstimated=INT
		public Assignment getTimeEstimatedAssignment_34() { return cTimeEstimatedAssignment_34; }
		
		//INT
		public RuleCall getTimeEstimatedINTTerminalRuleCall_34_0() { return cTimeEstimatedINTTerminalRuleCall_34_0; }
		
		//',"isReprocessedTask":'
		public Keyword getIsReprocessedTaskKeyword_35() { return cIsReprocessedTaskKeyword_35; }
		
		//isReprocessedTask=CADENA
		public Assignment getIsReprocessedTaskAssignment_36() { return cIsReprocessedTaskAssignment_36; }
		
		//CADENA
		public RuleCall getIsReprocessedTaskCADENATerminalRuleCall_36_0() { return cIsReprocessedTaskCADENATerminalRuleCall_36_0; }
		
		//',"idParentTask":'
		public Keyword getIdParentTaskKeyword_37() { return cIdParentTaskKeyword_37; }
		
		//idParentTask=INT
		public Assignment getIdParentTaskAssignment_38() { return cIdParentTaskAssignment_38; }
		
		//INT
		public RuleCall getIdParentTaskINTTerminalRuleCall_38_0() { return cIdParentTaskINTTerminalRuleCall_38_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_39() { return cRightCurlyBracketKeyword_39; }
	}
	
	
	private final RootElements pRoot;
	private final ProjectElements pProject;
	private final PhaseElements pPhase;
	private final TaskElements pTask;
	private final TerminalRule tCADENA;
	private final TerminalRule tDOUBLE;
	private final TerminalRule tDATE;
	private final TerminalRule tDATEHOUR;
	private final TerminalRule tSPACE;
	
	private final Grammar grammar;
	
	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public KPIGeneratorGrammarAccess(GrammarProvider grammarProvider,
			TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pRoot = new RootElements();
		this.pProject = new ProjectElements();
		this.pPhase = new PhaseElements();
		this.pTask = new TaskElements();
		this.tCADENA = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "co.edu.uniandes.KPIGenerator.CADENA");
		this.tDOUBLE = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "co.edu.uniandes.KPIGenerator.DOUBLE");
		this.tDATE = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "co.edu.uniandes.KPIGenerator.DATE");
		this.tDATEHOUR = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "co.edu.uniandes.KPIGenerator.DATEHOUR");
		this.tSPACE = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "co.edu.uniandes.KPIGenerator.SPACE");
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("co.edu.uniandes.KPIGenerator".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	
	
	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//Root:
	//	'[' projects+=Project (',' projects+=Project)* ']';
	public RootElements getRootAccess() {
		return pRoot;
	}
	
	public ParserRule getRootRule() {
		return getRootAccess().getRule();
	}
	
	//Project:
	//	{Project}
	//	'{"name":"' projectName=CADENA '","phases":[' phases+=Phase (',' phases+=Phase)* ']}';
	public ProjectElements getProjectAccess() {
		return pProject;
	}
	
	public ParserRule getProjectRule() {
		return getProjectAccess().getRule();
	}
	
	//Phase:
	//	{Phase} ','? '{"name":"' phaseName=CADENA '","tasks":[' tasks+=Task (',' tasks+=Task)* ']}';
	public PhaseElements getPhaseAccess() {
		return pPhase;
	}
	
	public ParserRule getPhaseRule() {
		return getPhaseAccess().getRule();
	}
	
	//Task:
	//	{Task}
	//	'{"id":' taskId=INT ',"name":"' taskName=CADENA '","useCase":"' useCase=CADENA '","sequenceNumber":'
	//	sequenceNumber=DOUBLE ',"startDate":"' startDate=(DATE | '-') '","dueDate":"' dueDate=(DATE | '-') '","isPrivate":'
	//	isPrivate=CADENA ',"progress":' progress=INT ',"status":"' statusName=CADENA '","statusText":"' statusText=CADENA
	//	'","assignedTo":"' assignedTo=CADENA '","createdDate":"' createdDate=DATEHOUR '","completedDate":"'
	//	completedDate=(DATEHOUR | '-') '","timeLoggedMin":' timeLoggedMin=INT ',"billableTime":' billableTime=INT
	//	',"completedOnTime":' completedOnTime=CADENA ',"timeEstimated":' timeEstimated=INT ',"isReprocessedTask":'
	//	isReprocessedTask=CADENA ',"idParentTask":' idParentTask=INT '}';
	public TaskElements getTaskAccess() {
		return pTask;
	}
	
	public ParserRule getTaskRule() {
		return getTaskAccess().getRule();
	}
	
	//terminal CADENA:
	//	('a'..'z' | 'A'..'Z' | 'Á' | 'á' | 'É' | 'é' | 'Í' | 'í' | 'Ó' | 'ó' | 'Ú' | 'ú' | '-' | ' ' | '|' | '.' | '(' | ')'
	//	| '/' | ':')+ '0'..'9'*+;
	public TerminalRule getCADENARule() {
		return tCADENA;
	}
	
	//terminal DOUBLE:
	//	INT '.' INT;
	public TerminalRule getDOUBLERule() {
		return tDOUBLE;
	}
	
	//terminal DATE:
	//	INT+ '/' INT+ '/' INT+;
	public TerminalRule getDATERule() {
		return tDATE;
	}
	
	//terminal DATEHOUR:
	//	DATE SPACE (INT ':' INT) SPACE ('AM' | 'PM');
	public TerminalRule getDATEHOURRule() {
		return tDATEHOUR;
	}
	
	//terminal SPACE:
	//	' ';
	public TerminalRule getSPACERule() {
		return tSPACE;
	}
	
	//terminal ID:
	//	'^'? ('a'..'z' | 'A'..'Z' | '_') ('a'..'z' | 'A'..'Z' | '_' | '0'..'9')*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	}
	
	//terminal INT returns ecore::EInt:
	//	'0'..'9'+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	}
	
	//terminal STRING:
	//	'"' ('\\' . | !('\\' | '"'))* '"' | "'" ('\\' . | !('\\' | "'"))* "'";
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	}
	
	//terminal ML_COMMENT:
	//	'/ *'->'* /';
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	}
	
	//terminal SL_COMMENT:
	//	'//' !('\n' | '\r')* ('\r'? '\n')?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	}
	
	//terminal WS:
	//	' ' | '\t' | '\r' | '\n'+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	}
	
	//terminal ANY_OTHER:
	//	.;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	}
}
