/*
 * generated by Xtext 2.10.0
 */
package co.edu.uniandes


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class KPIGeneratorRuntimeModule extends AbstractKPIGeneratorRuntimeModule {
}
