/*
 * generated by Xtext 2.10.0
 */
package co.edu.uniandes.serializer;

import co.edu.uniandes.services.KPIGeneratorGrammarAccess;
import com.google.inject.Inject;
import java.util.List;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.IGrammarAccess;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.nodemodel.INode;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.AbstractElementAlias;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.TokenAlias;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynNavigable;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynTransition;
import org.eclipse.xtext.serializer.sequencer.AbstractSyntacticSequencer;

@SuppressWarnings("all")
public class KPIGeneratorSyntacticSequencer extends AbstractSyntacticSequencer {

	protected KPIGeneratorGrammarAccess grammarAccess;
	protected AbstractElementAlias match_Phase_CommaKeyword_6_q;
	protected AbstractElementAlias match_Project_CommaKeyword_6_q;
	protected AbstractElementAlias match_Task_CommaKeyword_40_q;
	
	@Inject
	protected void init(IGrammarAccess access) {
		grammarAccess = (KPIGeneratorGrammarAccess) access;
		match_Phase_CommaKeyword_6_q = new TokenAlias(false, true, grammarAccess.getPhaseAccess().getCommaKeyword_6());
		match_Project_CommaKeyword_6_q = new TokenAlias(false, true, grammarAccess.getProjectAccess().getCommaKeyword_6());
		match_Task_CommaKeyword_40_q = new TokenAlias(false, true, grammarAccess.getTaskAccess().getCommaKeyword_40());
	}
	
	@Override
	protected String getUnassignedRuleCallToken(EObject semanticObject, RuleCall ruleCall, INode node) {
		return "";
	}
	
	
	@Override
	protected void emitUnassignedTokens(EObject semanticObject, ISynTransition transition, INode fromNode, INode toNode) {
		if (transition.getAmbiguousSyntaxes().isEmpty()) return;
		List<INode> transitionNodes = collectNodes(fromNode, toNode);
		for (AbstractElementAlias syntax : transition.getAmbiguousSyntaxes()) {
			List<INode> syntaxNodes = getNodesFor(transitionNodes, syntax);
			if (match_Phase_CommaKeyword_6_q.equals(syntax))
				emit_Phase_CommaKeyword_6_q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_Project_CommaKeyword_6_q.equals(syntax))
				emit_Project_CommaKeyword_6_q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_Task_CommaKeyword_40_q.equals(syntax))
				emit_Task_CommaKeyword_40_q(semanticObject, getLastNavigableState(), syntaxNodes);
			else acceptNodes(getLastNavigableState(), syntaxNodes);
		}
	}

	/**
	 * Ambiguous syntax:
	 *     ','?
	 *
	 * This ambiguous syntax occurs at:
	 *     tasks+=Task ']}' (ambiguity) (rule end)
	 */
	protected void emit_Phase_CommaKeyword_6_q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ','?
	 *
	 * This ambiguous syntax occurs at:
	 *     phases+=Phase ']}' (ambiguity) (rule end)
	 */
	protected void emit_Project_CommaKeyword_6_q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ','?
	 *
	 * This ambiguous syntax occurs at:
	 *     tags='"' '}' (ambiguity) (rule end)
	 *     tags=CADENA '}' (ambiguity) (rule end)
	 */
	protected void emit_Task_CommaKeyword_40_q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
}
